"""
Unit and integration tests for StructuralConnectivityEngine.
Verifies the extraction of unified Generative Principles from divergent Branching Points
and verifies O(1) Field Resonance and Structural Isomorphism mapping.
"""

import math
import numpy as np
import pytest

from core.topology.structural_connectivity_engine import (
    StructuralConnectivityEngine,
    BranchingPoint,
    GenerativePrinciple,
    StructuralResonance
)
from synaptic_architecture.inverse_mechanism_engine import (
    InverseMechanismEngine,
    ObservedTrajectory,
    BoundaryCondition
)
from core.physics.causal_field import CausalField, InformationVoxel


def test_generative_principle_extraction():
    engine = StructuralConnectivityEngine(mdl_threshold=1e-3)

    # Create 3 divergent branching points generated by an underlying sine wave with noise
    branches = []
    for i in range(3):
        phase_shift = i * 0.2
        noise_level = (i + 1) * 0.05
        states = []
        for t in range(20):
            # Underlying invariant baseline = 2.0, with sinusoidal modulation and noise
            val1 = 2.0 + math.sin(0.5 * t + phase_shift) + (np.random.rand() - 0.5) * noise_level
            val2 = 1.0 + math.cos(0.5 * t + phase_shift) + (np.random.rand() - 0.5) * noise_level
            states.append([val1, val2])

        branch = BranchingPoint(
            branch_id=f"wave_branch_{i}",
            context_domain="ocean_wave_simulation",
            observed_states=states,
            local_friction=1.0 + i * 0.1
        )
        branches.append(branch)

    # Extract single unified Generative Principle ('Sameness')
    principle = engine.extract_generative_principle("unified_ocean_wave", branches)

    assert principle.principle_id == "unified_ocean_wave"
    assert len(principle.topological_invariants) == 2
    # Baseline invariants should be around ~2.0 and ~1.0
    assert abs(principle.topological_invariants[0] - 2.0) < 0.5
    assert abs(principle.topological_invariants[1] - 1.0) < 0.5
    assert "harmonic_frequency" in principle.generative_grammar


def test_structural_isomorphism():
    engine = StructuralConnectivityEngine()

    # Two branches sharing same underlying wave structure
    states_a = [[math.sin(0.1 * t), math.cos(0.1 * t)] for t in range(15)]
    states_b = [[math.sin(0.1 * t + 0.01) + 0.05, math.cos(0.1 * t + 0.01) - 0.05] for t in range(15)]
    # One unrelated random branch
    states_c = [[(np.random.rand() - 0.5) * 10, (np.random.rand() - 0.5) * 10] for t in range(15)]

    branch_a = BranchingPoint("a", "domain1", states_a)
    branch_b = BranchingPoint("b", "domain2", states_b)
    branch_c = BranchingPoint("c", "domain3", states_c)

    iso_ab = engine.compute_structural_isomorphism(branch_a, branch_b)
    iso_ac = engine.compute_structural_isomorphism(branch_a, branch_c)

    # Isomorphism between structurally identical branches should be significantly higher
    assert iso_ab > 0.8
    assert iso_ab > iso_ac


def test_field_resonance_and_integration():
    # 1. Test Integration with InverseMechanismEngine
    inv_engine = InverseMechanismEngine()
    trajectories = [
        ObservedTrajectory("traj_1", "bound_1", [[1.0, 2.0], [1.2, 2.1], [1.5, 2.3]]),
        ObservedTrajectory("traj_2", "bound_2", [[0.9, 1.9], [1.1, 2.0], [1.4, 2.2]])
    ]

    principle = inv_engine.extract_generative_principle_from_trajectories(
        "traj_principle", trajectories, "causal_trajectories"
    )
    assert principle.principle_id == "traj_principle"

    # 2. Test Integration with CausalField
    causal_field = CausalField(dimensions=2)
    v1 = InformationVoxel("voxel_1", "Core", np.array([0.5, 0.5], dtype=np.float32))
    causal_field.add_voxel(v1)

    source_branch = BranchingPoint("src", "physical", [[1.0, 2.0], [1.2, 2.1], [1.5, 2.3]])
    resonance = causal_field.resonate_field_structure(
        principle, source_branch, "causal_field_wave"
    )

    assert resonance.isomorphism_score > 0.0
    assert len(resonance.converged_trajectory) == 3
    # Check that voxel potential was updated towards invariant target
    assert v1.potential > 0.0
