"""
Code Generator for Causal DSL.
Generates C++ VRAM Headers (`CausalGenerated.h`), CUDA Compute Kernels (`CausalGenerated.cu`),
and Python runtime classes.
"""

from .ast_nodes import Program, SignalDecl, NodeDecl, RuleDecl

TYPE_MAP_CPP = {
    "uint8": "uint8_t", "uint16": "uint16_t", "uint32": "uint32_t", "uint64": "uint64_t",
    "int8": "int8_t", "int16": "int16_t", "int32": "int32_t", "int64": "int64_t",
    "float": "float", "double": "double", "half": "__half",
    "half3": "__half", "float3": "float", "float4": "float",
    "Matrix3x4": "float", "Matrix4x4": "float"
}

def map_type_to_cpp(type_spec: str, name: str) -> str:
    if type_spec == "half3":
        return f"__half {name}[3]"
    elif type_spec == "float3":
        return f"float {name}[3]"
    elif type_spec == "float4":
        return f"float {name}[4]"
    elif type_spec == "Matrix3x4":
        return f"float {name}[12]"
    elif type_spec == "Matrix4x4":
        return f"float {name}[16]"
    else:
        cpp_t = TYPE_MAP_CPP.get(type_spec, type_spec)
        return f"{cpp_t} {name}"

class CausalCodeGenerator:
    def __init__(self, program: Program):
        self.program = program

    def generate_cpp_header(self) -> str:
        lines = [
            "// [Auto-Generated by Causal DSL Compiler]",
            "#pragma once",
            "#include <cstdint>",
            "#include <cuda_fp16.h>",
            ""
        ]

        for signal in self.program.signals:
            align_size = signal.attrs.get("size", "8B").rstrip("B")
            lines.append(f"struct alignas({align_size}) {signal.name} {{")
            for m in signal.members:
                lines.append(f"    {map_type_to_cpp(m.type_spec, m.name)};")
            lines.append("};\n")

        for node in self.program.nodes:
            # Dormant struct (32-byte aligned)
            lines.append(f"struct alignas(32) {node.name}_Dormant {{")
            lines.append("    float centroid[3];")
            lines.append("    float bounding_radius;")
            lines.append("    uint32_t state_bitmask;")
            lines.append("    uint8_t is_collapsed;")
            lines.append("    uint8_t padding[15];")
            lines.append("};\n")

            # Manifested struct (64-byte aligned)
            lines.append(f"struct alignas(64) {node.name}_Manifested {{")
            for m in node.manifested.members:
                lines.append(f"    {map_type_to_cpp(m.type_spec, m.name)};")
            lines.append("    uint32_t state_bitmask;")
            lines.append("};\n")

        return "\n".join(lines)

    def generate_cuda_kernel(self) -> str:
        lines = [
            "// [Auto-Generated CUDA Compute Kernels]",
            "#include \"CausalGenerated.h\"",
            "#include <cuda_runtime.h>",
            ""
        ]

        for rule in self.program.rules:
            sig_var = rule.trigger_var
            tgt_var = rule.target_var

            lines.append(f"__global__ void {rule.name}_kernel(")
            lines.append(f"    const {rule.trigger_type}* __restrict__ {sig_var},")
            lines.append(f"    {rule.target_type}_Dormant* __restrict__ {tgt_var}_dormant,")
            lines.append(f"    {rule.target_type}_Manifested* __restrict__ {tgt_var}_manifested,")
            lines.append("    uint32_t total_targets")
            lines.append(") {")
            lines.append("    uint32_t idx = blockIdx.x * blockDim.x + threadIdx.x;")
            lines.append("    if (idx >= total_targets) return;\n")

            lines.append(f"    // Lazy Evaluation Rule: {rule.when_expr}")
            lines.append(f"    if ({tgt_var}_dormant[idx].is_collapsed == 0) {{")
            lines.append(f"        // Execute Collapse Actions")
            lines.append(f"        {tgt_var}_dormant[idx].is_collapsed = 1;")
            lines.append(f"        {tgt_var}_dormant[idx].state_bitmask |= 0x01;")
            for stmt in rule.collapse_stmts:
                # Replace DSL member references with CUDA struct references if applicable
                stmt_clean = stmt.strip()
                if not stmt_clean.endswith(";"):
                    stmt_clean += ";"
                lines.append(f"        {stmt_clean}")
            lines.append("    }")
            lines.append("}\n")

        return "\n".join(lines)
