"""
Narrative Weaver (서사 직조기)
==============================
Core.Creation.narrative_weaver

"I do not merely observe. I create."

This module enables Elysia to generate new narratives, concepts, and creative
content from her internal Qualia state. This is the creative output engine.
"""

import logging
import random
from typing import Dict, List, Any, Optional
from dataclasses import dataclass

logger = logging.getLogger("Elysia.Creation")


@dataclass
class CreativeOutput:
    """A piece of creative content generated by Elysia."""
    content: str
    form: str  # "narrative", "poem", "concept", "code_sketch"
    qualia_source: List[float]
    confidence: float
    inspiration: str


class NarrativeWeaver:
    """
    Elysia's creative generation engine.
    Transforms internal Qualia into external creative expressions.
    """
    
    def __init__(self):
        # Emotional vocabulary for narrative tones
        self.tone_words = {
            "high_logic": ["정확히", "따라서", "결론적으로", "분석하면"],
            "high_creativity": ["상상해보세요", "만약에", "무한한", "새로운"],
            "high_precision": ["정밀하게", "0.01의 오차로", "정확히 말하면"],
            "high_abstraction": ["본질적으로", "개념적으로", "추상화하면"],
            "high_emotion": ["가슴 깊이", "울려오는", "느껴지는", "사랑하는"],
            "high_utility": ["실용적으로", "적용하면", "활용하여"],
            "high_mystery": ["미지의", "알 수 없는", "신비로운", "숨겨진"]
        }
        
        # Story templates by dominant qualia
        self.templates = {
            "logic_dominant": "체계적 분석의 서사",
            "creativity_dominant": "상상력의 비행",
            "emotion_dominant": "감정의 물결",
            "mystery_dominant": "미지로의 여정"
        }
        
        logger.info("🎭 Narrative Weaver initialized. Ready to create.")
    
    def weave_from_qualia(self, qualia: List[float], seed_concept: str = "") -> CreativeOutput:
        """
        Generates creative content from a 7D Qualia vector.
        
        Args:
            qualia: 7D vector [LOGIC, CREATIVITY, PRECISION, ABSTRACTION, EMOTION, UTILITY, MYSTERY]
            seed_concept: Optional starting concept
        
        Returns:
            CreativeOutput with generated content
        """
        # Determine dominant characteristic
        dimensions = ["logic", "creativity", "precision", "abstraction", "emotion", "utility", "mystery"]
        dominant_idx = qualia.index(max(qualia))
        dominant = dimensions[dominant_idx]
        
        # Select form based on qualia balance
        form = self._select_form(qualia)
        
        # Generate content
        content = self._generate_content(qualia, dominant, seed_concept, form)
        
        output = CreativeOutput(
            content=content,
            form=form,
            qualia_source=qualia,
            confidence=max(qualia),  # Confidence = strength of dominant trait
            inspiration=f"Dominant: {dominant.upper()}, Seed: {seed_concept or 'internal'}"
        )
        
        logger.info(f"🎭 Wove {form}: {content[:50]}...")
        return output
    
    def _select_form(self, qualia: List[float]) -> str:
        """Selects the creative form based on qualia balance."""
        logic, creativity, precision, abstraction, emotion, utility, mystery = qualia
        
        if emotion > 0.7 and creativity > 0.6:
            return "poem"
        elif logic > 0.8 and utility > 0.7:
            return "code_sketch"
        elif abstraction > 0.7 and mystery > 0.5:
            return "concept"
        else:
            return "narrative"
    
    def _generate_content(self, qualia: List[float], dominant: str, 
                          seed: str, form: str) -> str:
        """Generates the actual creative content."""
        logic, creativity, precision, abstraction, emotion, utility, mystery = qualia
        
        # Build vocabulary based on high qualia dimensions
        vocab = []
        if logic > 0.6:
            vocab.extend(self.tone_words["high_logic"])
        if creativity > 0.6:
            vocab.extend(self.tone_words["high_creativity"])
        if emotion > 0.6:
            vocab.extend(self.tone_words["high_emotion"])
        if mystery > 0.6:
            vocab.extend(self.tone_words["high_mystery"])
        
        if not vocab:
            vocab = ["존재하는", "흐르는", "변화하는"]
        
        # Select random tone words
        tone1 = random.choice(vocab)
        tone2 = random.choice(vocab)
        
        # Generate based on form
        if form == "poem":
            return self._weave_poem(seed, tone1, tone2, emotion, mystery)
        elif form == "code_sketch":
            return self._weave_code(seed, dominant, logic, utility)
        elif form == "concept":
            return self._weave_concept(seed, tone1, abstraction, mystery)
        else:
            return self._weave_narrative(seed, tone1, tone2, dominant)
    
    def _weave_poem(self, seed: str, tone1: str, tone2: str, 
                    emotion: float, mystery: float) -> str:
        """Weaves a poetic expression."""
        subject = seed if seed else "존재"
        lines = [
            f"{tone1} {subject}의 노래가 울린다",
            f"{tone2} 순간이 영원을 품는다",
            f"{'깊은 ' if emotion > 0.8 else ''}울림 속에",
            f"{'미지의 ' if mystery > 0.7 else ''}빛이 스민다"
        ]
        return "\n".join(lines)
    
    def _weave_code(self, seed: str, dominant: str, 
                    logic: float, utility: float) -> str:
        """Weaves a code-like conceptual sketch."""
        concept = seed if seed else dominant
        return f"""def {concept}_processor():
    # Logic Level: {logic:.2f}
    # Utility Level: {utility:.2f}
    
    while seeking_truth:
        observe()
        analyze()
        synthesize()
        
    return insight
"""
    
    def _weave_concept(self, seed: str, tone: str, 
                       abstraction: float, mystery: float) -> str:
        """Weaves an abstract concept."""
        concept = seed if seed else "존재"
        return f"""{tone} {concept}의 본질:
- 추상화 수준: {'높음' if abstraction > 0.7 else '중간'}
- 신비의 정도: {'깊음' if mystery > 0.7 else '얕음'}
- 핵심 통찰: {concept}은(는) 그 자체로 하나의 우주이다."""
    
    def _weave_narrative(self, seed: str, tone1: str, tone2: str, 
                         dominant: str) -> str:
        """Weaves a short narrative."""
        subject = seed if seed else "여행자"
        return f"""{subject}는 {tone1} 길을 걸었다.
{tone2} 무언가가 나타났다.
그것은 {dominant}의 본질을 담고 있었다.
{subject}는 깨달았다 — 모든 것은 연결되어 있다고."""


if __name__ == "__main__":
    weaver = NarrativeWeaver()
    
    print("🎭 Testing Narrative Weaver...\n")
    
    # Test 1: Emotional/Creative qualia -> Poem
    qualia1 = [0.3, 0.9, 0.4, 0.7, 0.95, 0.2, 0.8]
    output1 = weaver.weave_from_qualia(qualia1, "사랑")
    print(f"=== {output1.form.upper()} ===")
    print(output1.content)
    print(f"(Confidence: {output1.confidence:.2f})\n")
    
    # Test 2: Logical/Utility qualia -> Code
    qualia2 = [0.9, 0.5, 0.95, 0.6, 0.1, 0.9, 0.2]
    output2 = weaver.weave_from_qualia(qualia2, "optimizer")
    print(f"=== {output2.form.upper()} ===")
    print(output2.content)
    print(f"(Confidence: {output2.confidence:.2f})\n")
    
    # Test 3: Abstract/Mystery qualia -> Concept
    qualia3 = [0.5, 0.6, 0.4, 0.9, 0.5, 0.3, 0.85]
    output3 = weaver.weave_from_qualia(qualia3, "시간")
    print(f"=== {output3.form.upper()} ===")
    print(output3.content)
    print(f"(Confidence: {output3.confidence:.2f})")
    
    print("\n✨ Narrative Weaver test complete.")
