
import json
import logging
from typing import List, Dict, Any, Optional
from Core.Mind.hippocampus import Hippocampus
from Core.Ethics.conscience import Conscience

logger = logging.getLogger("PlanningCortex")

class PlanningCortex:
    """
    The Prefrontal Cortex of Elysia.
    Responsible for breaking down high-level goals into executable plans.
    Integrates with Memory (Hippocampus) and Ethics (Conscience).
    """
    
    def __init__(self, hippocampus: Hippocampus, conscience: Conscience):
        self.hippocampus = hippocampus
        self.conscience = conscience
        logger.info("✅ Planning Cortex initialized")

    def develop_plan(self, goal: str) -> List[Dict[str, Any]]:
        """
        Develops a step-by-step plan to achieve a given goal.
        """
        logger.info(f"🧠 Developing plan for goal: {goal}")
        
        # 1. Ethical Check
        if not self.conscience.evaluate_action("planning", {"goal": goal}):
            logger.warning(f"⛔ Plan rejected by Conscience: {goal}")
            return []

        # 2. Context Retrieval (Memory)
        context = self.hippocampus.retrieve(goal)
        
        # 3. Plan Generation (Simulated LLM for now, can be hooked to real API later)
        # In a real scenario, this would call an LLM with the goal and context.
        # For this phase, we will implement a rule-based planner for specific tasks
        # to demonstrate agency without needing an external API key yet.
        
        plan = self._heuristic_planner(goal)
        
        if plan:
            logger.info(f"📋 Plan generated with {len(plan)} steps.")
        else:
            logger.warning("⚠️ Could not generate a plan for this goal.")
            
        return plan

    def _heuristic_planner(self, goal: str) -> List[Dict[str, Any]]:
        """
        A simple heuristic planner for demonstration purposes.
        """
        plan = []
        goal_lower = goal.lower()
        
        if "write" in goal_lower and (".txt" in goal_lower or "file" in goal_lower):
            # Example: "Write a poem to test.txt"
            filename = "test_output.txt"
            # Try to extract filename from goal
            words = goal.split()
            for word in words:
                if ".txt" in word:
                    filename = word
                    
            plan.append({
                "tool": "write_to_file",
                "parameters": {
                    "filename": filename,
                    "content": "This is a test file generated by Elysia's Planning Cortex."
                }
            })
        elif "search" in goal_lower or "research" in goal_lower:
            # Example: "Research quantum physics"
            plan.append({
                "tool": "web_search",
                "parameters": {
                    "query": goal.replace("research", "").replace("search", "").strip()
                }
            })
            plan.append({
                "tool": "write_to_file",
                "parameters": {
                    "filename": "research_notes.txt",
                    "content": "Summary of research..."
                }
            })
            
        return plan
