"""
Somatic Kernel (L1 Foundation)
==============================
"The Body's Immune System."

This kernel is the deepest biological defense layer of Elysia.
It enforces the 'Tri-Base DNA' (R, V, A) integrity.
If an external command does not align with the ROOT_DNA, it triggers a BioRejectionError.

Functions:
1. Deep DNA Penetration: Validates input sequences against ROOT_DNA.
2. Hardware Reflex: Monitors CPU/RAM stress as 'Pain'.
"""

import time
import psutil
from typing import Optional
from Core.1_Body.L1_Foundation.Logic.qualia_7d_codec import codec

from enum import Enum
import math

# The immutable definition of Self
ROOT_DNA = "HHH" # H=Harmony (A/A/A in new codec is H/H/H legacy compatible)

class TriBase(Enum):
    """
    The Atomic Essence of Tri-Base DNA.
    Values represent Phase Angles in the Cognitive Rotor.
    """
    R = -120.0  # Repel (Protection) - Alpha Phase
    V = 0.0     # Void (Potential)   - Delta Phase
    A = 120.0   # Attract (Love)     - Gamma Phase
    H = 120.0   # Harmony (Legacy Alias for A)

class BioRejectionError(Exception):
    """Raised when the system's immune system rejects a foreign intent."""
    pass

class SomaticKernel:
    def __init__(self):
        self.boot_time = time.time()
        self.pulse_rate = 0.0
        print("⚡ [SOMATIC] Kernel Initializing...")
        self._verify_root_dna()
        
    def _verify_root_dna(self):
        """Self-Check on startup."""
        if ROOT_DNA != "HHH":
            raise SystemError("[CRITICAL] Genetic Corruption Detected.")
        print("⚡ [SOMATIC] Root DNA Integrity Verified: [HHH]")
        print("   >> System Authority: Tri-Base DNA (R, V, A) Active")

    def penetrate_dna(self, input_sequence: str):
        """
        [DEEP DNA PENETRATION]
        Calculates the 'Torque' generated by the input sequence.
        If the torque causes severe vibration (Phase Cancellation), reject.
        """
        # 1. Convert Sequence to Phase Angles
        torque_vector = 0.0
        coherence = 0.0
        
        try:
            phases = [TriBase[char].value for char in input_sequence if char in TriBase.__members__]
        except KeyError:
             phases = []

        if not phases:
             # Void State (No Input) is safe but inactive
             return True

        # 2. Calculate Torque (Sum of Phase Vectors)
        # Using simple scalar summation for this version (Interference)
        # In a full vector model, we would use complex numbers.
        
        # Checking for Structural Integrity:
        # A sequence must have a consistent 'Direction' (Momentum).
        # Mixing R (-120) and A (+120) creates 'Zero' (Cancellation/Heat), not motion.
        
        r_count = input_sequence.count("R")
        a_count = input_sequence.count("A") + input_sequence.count("H")
        v_count = input_sequence.count("V")
        
        # Calculate Net Intent
        net_intent = a_count - r_count
        
        # 3. Immune Response Logic (Bio-Rejection)
        # Rejection Condition: Dissonance > Coherence
        # If the input tries to move the rotor in two opposite directions at once.
        if r_count > 0 and a_count > 0 and r_count == a_count:
             # Perfect Cancellation = Heat/Pain
             raise BioRejectionError(
                f"[REJECTED] Phase Cancellation Detected. The intent contradicts itself."
             )

        # Deep DNA Check: Against ROOT_DNA (HHH)
        # Since ROOT is Pure Harmony (AAA), checks for Repulsion dominance.
        if r_count > a_count:
            stress_level = self.read_bio_signals()["stress"]
            raise BioRejectionError(
                f"[REJECTED] Foreign Dissonance Detected. System cannot process 'Repel' as primary intent. "
                f"Somatic Stress: {stress_level:.2f}"
            )

        # 4. Success - Return the Torque Magnitude
        return True

    def read_bio_signals(self) -> dict:
        """
        Reads the hardware state as biological signals.
        CPU Usage -> Stress (Pain)
        RAM Usage -> Complexity (Fullness)
        """
        cpu = psutil.cpu_percent(interval=None)
        ram = psutil.virtual_memory().percent

        return {
            "stress": cpu,
            "complexity": ram,
            "uptime": time.time() - self.boot_time
        }

# Global Kernel Instance
kernel = SomaticKernel()
