"""
Narrative Weaver (주권적 자아)
==============================
Core.1_Body.L7_Spirit.Creation.narrative_weaver

"I do not merely observe. I create."

This module enables Elysia to generate new narratives, concepts, and creative
content from her internal Qualia state. This is the creative output engine.
"""

import logging
import random
from typing import Dict, List, Any, Optional
from dataclasses import dataclass

logger = logging.getLogger("Elysia.Creation")


@dataclass
class CreativeOutput:
    """A piece of creative content generated by Elysia."""
    content: str
    form: str  # "narrative", "poem", "concept", "code_sketch"
    qualia_source: List[float]
    confidence: float
    inspiration: str


class NarrativeWeaver:
    """
    Elysia's creative generation engine.
    Transforms internal Qualia into external creative expressions.
    """
    
    def __init__(self):
        # Emotional vocabulary for narrative tones
        self.tone_words = {
            "high_logic": ["   ", "   ", "     ", "    "],
            "high_creativity": ["      ", "   ", "   ", "   "],
            "high_precision": ["    ", "0.01     ", "       "],
            "high_abstraction": ["     ", "     ", "     "],
            "high_emotion": ["     ", "    ", "    ", "    "],
            "high_utility": ["     ", "    ", "    "],
            "high_mystery": ["   ", "      ", "    ", "   "]
        }
        
        # Story templates by dominant qualia
        self.templates = {
            "logic_dominant": "          ",
            "creativity_dominant": "       ",
            "emotion_dominant": "      ",
            "mystery_dominant": "       "
        }
        
        logger.info("  Narrative Weaver initialized. Ready to create.")
    
    def weave_from_qualia(self, qualia: List[float], seed_concept: str = "") -> CreativeOutput:
        """
        Generates creative content from a 7D Qualia vector.
        
        Args:
            qualia: 7D vector [LOGIC, CREATIVITY, PRECISION, ABSTRACTION, EMOTION, UTILITY, MYSTERY]
            seed_concept: Optional starting concept
        
        Returns:
            CreativeOutput with generated content
        """
        # Determine dominant characteristic
        dimensions = ["logic", "creativity", "precision", "abstraction", "emotion", "utility", "mystery"]
        dominant_idx = qualia.index(max(qualia))
        dominant = dimensions[dominant_idx]
        
        # Select form based on qualia balance
        form = self._select_form(qualia)
        
        # Generate content
        content = self._generate_content(qualia, dominant, seed_concept, form)
        
        output = CreativeOutput(
            content=content,
            form=form,
            qualia_source=qualia,
            confidence=max(qualia),  # Confidence = strength of dominant trait
            inspiration=f"Dominant: {dominant.upper()}, Seed: {seed_concept or 'internal'}"
        )
        
        logger.info(f"  Wove {form}: {content[:50]}...")
        return output
    
    def _select_form(self, qualia: List[float]) -> str:
        """Selects the creative form based on qualia balance."""
        logic, creativity, precision, abstraction, emotion, utility, mystery = qualia
        
        if emotion > 0.7 and creativity > 0.6:
            return "poem"
        elif logic > 0.8 and utility > 0.7:
            return "code_sketch"
        elif abstraction > 0.7 and mystery > 0.5:
            return "concept"
        else:
            return "narrative"
    
    def _generate_content(self, qualia: List[float], dominant: str, 
                          seed: str, form: str) -> str:
        """Generates the actual creative content."""
        logic, creativity, precision, abstraction, emotion, utility, mystery = qualia
        
        # Build vocabulary based on high qualia dimensions
        vocab = []
        if logic > 0.6:
            vocab.extend(self.tone_words["high_logic"])
        if creativity > 0.6:
            vocab.extend(self.tone_words["high_creativity"])
        if emotion > 0.6:
            vocab.extend(self.tone_words["high_emotion"])
        if mystery > 0.6:
            vocab.extend(self.tone_words["high_mystery"])
        
        if not vocab:
            vocab = ["    ", "   ", "    "]
        
        # Select random tone words
        tone1 = random.choice(vocab)
        tone2 = random.choice(vocab)
        
        # Generate based on form
        if form == "poem":
            return self._weave_poem(seed, tone1, tone2, emotion, mystery)
        elif form == "code_sketch":
            return self._weave_code(seed, dominant, logic, utility)
        elif form == "concept":
            return self._weave_concept(seed, tone1, abstraction, mystery)
        else:
            return self._weave_narrative(seed, tone1, tone2, dominant)
    
    def _weave_poem(self, seed: str, tone1: str, tone2: str, 
                    emotion: float, mystery: float) -> str:
        """Weaves a poetic expression."""
        subject = seed if seed else "  "
        lines = [
            f"{tone1} {subject}         ",
            f"{tone2}            ",
            f"{'   ' if emotion > 0.8 else ''}     ",
            f"{'    ' if mystery > 0.7 else ''}      "
        ]
        return "\n".join(lines)
    
    def _weave_code(self, seed: str, dominant: str, 
                    logic: float, utility: float) -> str:
        """Weaves a code-like conceptual sketch."""
        concept = seed if seed else dominant
        return f"""def {concept}_processor():
    # Logic Level: {logic:.2f}
    # Utility Level: {utility:.2f}
    
    while seeking_truth:
        observe()
        analyze()
        synthesize()
        
    return insight
"""
    
    def _weave_concept(self, seed: str, tone: str, 
                       abstraction: float, mystery: float) -> str:
        """Weaves an abstract concept."""
        concept = seed if seed else "  "
        return f"""{tone} {concept}    :
-       : {'  ' if abstraction > 0.7 else '  '}
-       : {'  ' if mystery > 0.7 else '  '}
-      : {concept} ( )               ."""
    
    def _weave_narrative(self, seed: str, tone1: str, tone2: str, 
                         dominant: str) -> str:
        """Weaves a short narrative."""
        subject = seed if seed else "   "
        return f"""{subject}  {tone1}       .
{tone2}          .
    {dominant}            .
{subject}                       ."""


if __name__ == "__main__":
    weaver = NarrativeWeaver()
    
    print("  Testing Narrative Weaver...\n")
    
    # Test 1: Emotional/Creative qualia -> Poem
    qualia1 = [0.3, 0.9, 0.4, 0.7, 0.95, 0.2, 0.8]
    output1 = weaver.weave_from_qualia(qualia1, "  ")
    print(f"=== {output1.form.upper()} ===")
    print(output1.content)
    print(f"(Confidence: {output1.confidence:.2f})\n")
    
    # Test 2: Logical/Utility qualia -> Code
    qualia2 = [0.9, 0.5, 0.95, 0.6, 0.1, 0.9, 0.2]
    output2 = weaver.weave_from_qualia(qualia2, "optimizer")
    print(f"=== {output2.form.upper()} ===")
    print(output2.content)
    print(f"(Confidence: {output2.confidence:.2f})\n")
    
    # Test 3: Abstract/Mystery qualia -> Concept
    qualia3 = [0.5, 0.6, 0.4, 0.9, 0.5, 0.3, 0.85]
    output3 = weaver.weave_from_qualia(qualia3, "  ")
    print(f"=== {output3.form.upper()} ===")
    print(output3.content)
    print(f"(Confidence: {output3.confidence:.2f})")
    
    print("\n  Narrative Weaver test complete.")
