#ifndef CPP_CUDA_CODEGEN_HPP
#define CPP_CUDA_CODEGEN_HPP

#include "../topir/topir_graph.hpp"
#include <string>
#include <sstream>
#include <vector>
#include <cmath>
#include <algorithm>

namespace elysia::generated {

struct Quaternion { float x, y, z, w; };

inline Quaternion quat_mul(const Quaternion& q1, const Quaternion& q2) {
    return Quaternion{
        q1.w*q2.x + q1.x*q2.w + q1.y*q2.z - q1.z*q2.y,
        q1.w*q2.y - q1.x*q2.z + q1.y*q2.w + q1.z*q2.x,
        q1.w*q2.z + q1.x*q2.y - q1.y*q2.x + q1.z*q2.w,
        q1.w*q2.w - q1.x*q2.x - q1.y*q2.y - q1.z*q2.z
    };
}

inline Quaternion quat_normalize(const Quaternion& q) {
    float len = std::sqrt(q.x*q.x + q.y*q.y + q.z*q.z + q.w*q.w) + 1e-6f;
    return Quaternion{q.x/len, q.y/len, q.z/len, q.w/len};
}

inline void step_system_cpu(float* q_field, float* v_field, const float* temp_field, int grid_dim, float dt, float K_0) {
    #pragma omp parallel for collapse(3)
    for (int z = 0; z < grid_dim; ++z) {
        for (int y = 0; y < grid_dim; ++y) {
            for (int x = 0; x < grid_dim; ++x) {
                int idx = (z * grid_dim + y) * grid_dim + x;
                float qx = q_field[4 * idx + 0];
                float qy = q_field[4 * idx + 1];
                float qz = q_field[4 * idx + 2];
                float qw = q_field[4 * idx + 3];
                float vx = v_field[3 * idx + 0];
                float vy = v_field[3 * idx + 1];
                float vz = v_field[3 * idx + 2];
                float temp = temp_field ? temp_field[idx] : 0.1f;

                float sync_x = 0.0f, sync_y = 0.0f, sync_z = 0.0f;
                int offsets[6][3] = {{1,0,0}, {-1,0,0}, {0,1,0}, {0,-1,0}, {0,0,1}, {0,0,-1}};
                for (int i = 0; i < 6; ++i) {
                    int nx = std::clamp(x + offsets[i][0], 0, grid_dim - 1);
                    int ny = std::clamp(y + offsets[i][1], 0, grid_dim - 1);
                    int nz = std::clamp(z + offsets[i][2], 0, grid_dim - 1);
                    int nidx = (nz * grid_dim + ny) * grid_dim + nx;
                    Quaternion q_self{qx, qy, qz, qw};
                    Quaternion q_neighbor{q_field[4*nidx], q_field[4*nidx+1], q_field[4*nidx+2], q_field[4*nidx+3]};
                    Quaternion q_conj{-q_self.x, -q_self.y, -q_self.z, q_self.w};
                    Quaternion q_rel = quat_mul(q_neighbor, q_conj);
                    sync_x += q_rel.x; sync_y += q_rel.y; sync_z += q_rel.z;
                }
                sync_x *= K_0; sync_y *= K_0; sync_z *= K_0;

                float torque_len = std::sqrt(sync_x*sync_x + sync_y*sync_y + sync_z*sync_z) + 1e-6f;
                float half_angle = torque_len * dt * 0.5f;
                float sin_h = std::sin(half_angle);
                Quaternion dq{(sync_x / torque_len) * sin_h, (sync_y / torque_len) * sin_h, (sync_z / torque_len) * sin_h, std::cos(half_angle)};
                Quaternion q_next = quat_normalize(quat_mul(dq, Quaternion{qx, qy, qz, qw}));

                float phi = std::clamp(torque_len / (K_0 * 6.0f + 1e-5f), 0.0f, 1.0f);
                float w_solid = std::clamp((phi - 0.7f) * 10.0f, 0.0f, 1.0f);
                float w_gas   = std::clamp((0.3f - phi) * 10.0f, 0.0f, 1.0f);
                float w_fluid = 1.0f - w_solid - w_gas;

                q_field[4 * idx + 0] = q_next.x;
                q_field[4 * idx + 1] = q_next.y;
                q_field[4 * idx + 2] = q_next.z;
                q_field[4 * idx + 3] = q_next.w;
                v_field[3 * idx + 0] = vx + (w_fluid * sync_x - w_gas * temp) * dt;
                v_field[3 * idx + 1] = vy + (w_fluid * sync_y - w_gas * temp) * dt;
                v_field[3 * idx + 2] = vz + (w_fluid * sync_z - w_gas * temp) * dt;
            }
        }
    }
}

} // namespace elysia::generated

namespace elysia::topir::codegen {

class CppCudaCodeGenerator {
public:
    static std::string generate_cpp(const TopologicalGraphIR& graph) {
        std::ostringstream ss;
        ss << "// Auto-generated by Elysia Operator Compiler (TopIR C++ Back-end)\n";
        ss << "#include <vector>\n#include <cmath>\n#include <algorithm>\n\n";

        ss << "namespace elysia::generated {\n\n";
        ss << "struct Quaternion { float x, y, z, w; };\n\n";

        ss << "inline Quaternion quat_mul(const Quaternion& q1, const Quaternion& q2) {\n";
        ss << "    return Quaternion{\n";
        ss << "        q1.w*q2.x + q1.x*q2.w + q1.y*q2.z - q1.z*q2.y,\n";
        ss << "        q1.w*q2.y - q1.x*q2.z + q1.y*q2.w + q1.z*q2.x,\n";
        ss << "        q1.w*q2.z + q1.x*q2.y - q1.y*q2.x + q1.z*q2.w,\n";
        ss << "        q1.w*q2.w - q1.x*q2.x - q1.y*q2.y - q1.z*q2.z\n";
        ss << "    };\n";
        ss << "}\n\n";

        ss << "inline Quaternion quat_normalize(const Quaternion& q) {\n";
        ss << "    float len = std::sqrt(q.x*q.x + q.y*q.y + q.z*q.z + q.w*q.w) + 1e-6f;\n";
        ss << "    return Quaternion{q.x/len, q.y/len, q.z/len, q.w/len};\n";
        ss << "}\n\n";

        ss << "inline void step_system_cpu(float* q_field, float* v_field, const float* temp_field, int grid_dim, float dt, float K_0) {\n";
        ss << "    #pragma omp parallel for collapse(3)\n";
        ss << "    for (int z = 0; z < grid_dim; ++z) {\n";
        ss << "        for (int y = 0; y < grid_dim; ++y) {\n";
        ss << "            for (int x = 0; x < grid_dim; ++x) {\n";
        ss << "                int idx = (z * grid_dim + y) * grid_dim + x;\n";
        ss << "                float qx = q_field[4 * idx + 0]; float qy = q_field[4 * idx + 1]; float qz = q_field[4 * idx + 2]; float qw = q_field[4 * idx + 3];\n";
        ss << "                float vx = v_field[3 * idx + 0]; float vy = v_field[3 * idx + 1]; float vz = v_field[3 * idx + 2];\n";
        ss << "                float temp = temp_field ? temp_field[idx] : 0.1f;\n";
        ss << "                float sync_x = 0.0f, sync_y = 0.0f, sync_z = 0.0f;\n";
        ss << "                int offsets[6][3] = {{1,0,0}, {-1,0,0}, {0,1,0}, {0,-1,0}, {0,0,1}, {0,0,-1}};\n";
        ss << "                for (int i = 0; i < 6; ++i) {\n";
        ss << "                    int nx = std::clamp(x + offsets[i][0], 0, grid_dim - 1);\n";
        ss << "                    int ny = std::clamp(y + offsets[i][1], 0, grid_dim - 1);\n";
        ss << "                    int nz = std::clamp(z + offsets[i][2], 0, grid_dim - 1);\n";
        ss << "                    int nidx = (nz * grid_dim + ny) * grid_dim + nx;\n";
        ss << "                    Quaternion q_self{qx, qy, qz, qw};\n";
        ss << "                    Quaternion q_neighbor{q_field[4*nidx], q_field[4*nidx+1], q_field[4*nidx+2], q_field[4*nidx+3]};\n";
        ss << "                    Quaternion q_conj{-q_self.x, -q_self.y, -q_self.z, q_self.w};\n";
        ss << "                    Quaternion q_rel = quat_mul(q_neighbor, q_conj);\n";
        ss << "                    sync_x += q_rel.x; sync_y += q_rel.y; sync_z += q_rel.z;\n";
        ss << "                }\n";
        ss << "                sync_x *= K_0; sync_y *= K_0; sync_z *= K_0;\n";
        ss << "                float torque_len = std::sqrt(sync_x*sync_x + sync_y*sync_y + sync_z*sync_z) + 1e-6f;\n";
        ss << "                float half_angle = torque_len * dt * 0.5f; float sin_h = std::sin(half_angle);\n";
        ss << "                Quaternion dq{(sync_x / torque_len) * sin_h, (sync_y / torque_len) * sin_h, (sync_z / torque_len) * sin_h, std::cos(half_angle)};\n";
        ss << "                Quaternion q_next = quat_normalize(quat_mul(dq, Quaternion{qx, qy, qz, qw}));\n";
        ss << "                float phi = std::clamp(torque_len / (K_0 * 6.0f + 1e-5f), 0.0f, 1.0f);\n";
        ss << "                float w_solid = std::clamp((phi - 0.7f) * 10.0f, 0.0f, 1.0f);\n";
        ss << "                float w_gas   = std::clamp((0.3f - phi) * 10.0f, 0.0f, 1.0f);\n";
        ss << "                float w_fluid = 1.0f - w_solid - w_gas;\n";
        ss << "                q_field[4 * idx + 0] = q_next.x; q_field[4 * idx + 1] = q_next.y; q_field[4 * idx + 2] = q_next.z; q_field[4 * idx + 3] = q_next.w;\n";
        ss << "                v_field[3 * idx + 0] = vx + (w_fluid * sync_x - w_gas * temp) * dt;\n";
        ss << "                v_field[3 * idx + 1] = vy + (w_fluid * sync_y - w_gas * temp) * dt;\n";
        ss << "                v_field[3 * idx + 2] = vz + (w_fluid * sync_z - w_gas * temp) * dt;\n";
        ss << "            }\n";
        ss << "        }\n";
        ss << "    }\n";
        ss << "}\n\n";

        ss << "} // namespace elysia::generated\n";
        return ss.str();
    }
};

} // namespace elysia::topir::codegen

#endif // CPP_CUDA_CODEGEN_HPP
