#ifndef HLSL_CODEGEN_HPP
#define HLSL_CODEGEN_HPP

#include "../topir/topir_graph.hpp"
#include <string>
#include <sstream>

namespace elysia::topir::codegen {

class HLSLCodeGenerator {
public:
    static std::string generate_hlsl(const TopologicalGraphIR& graph) {
        std::ostringstream ss;
        ss << "// Auto-generated by Elysia Operator Compiler (TopIR HLSL Back-end)\n";
        ss << "// Target: Direct3D12 / Vulkan Compute Shader (SM 6.5+)\n\n";

        ss << "cbuffer SystemConstants : register(b0) {\n";
        ss << "    float4 g_Params; // x: dt, y: K_0, z: gamma, w: Temp\n";
        ss << "    uint3  g_GridSize;\n";
        ss << "};\n\n";

        ss << "RWTexture3D<float4> g_QField    : register(u0); // Quaternion Rotor Field (x, y, z, w)\n";
        ss << "RWTexture3D<float4> g_VField    : register(u1); // Velocity Field (vx, vy, vz, reserved)\n";
        ss << "Texture3D<float>    g_TempField : register(t0); // Temperature Field\n\n";

        ss << "SamplerState g_LinearSampler : register(s0);\n\n";

        ss << "float4 quat_mul(float4 q1, float4 q2) {\n";
        ss << "    return float4(\n";
        ss << "        q1.w*q2.xyz + q2.w*q1.xyz + cross(q1.xyz, q2.xyz),\n";
        ss << "        q1.w*q2.w - dot(q1.xyz, q2.xyz)\n";
        ss << "    );\n";
        ss << "}\n\n";

        ss << "float4 quat_conj(float4 q) {\n";
        ss << "    return float4(-q.xyz, q.w);\n";
        ss << "}\n\n";

        ss << "[numthreads(8, 8, 8)]\n";
        ss << "void CS_EvolveSystem(uint3 dispatchThreadID : SV_DispatchThreadID) {\n";
        ss << "    if (any(dispatchThreadID >= g_GridSize)) return;\n\n";

        ss << "    float3 uvw = (float3(dispatchThreadID) + 0.5f) / float3(g_GridSize);\n";
        ss << "    float dt = g_Params.x;\n";
        ss << "    float K_0 = g_Params.y;\n";
        ss << "    float temp = g_TempField.SampleLevel(g_LinearSampler, uvw, 0);\n\n";

        ss << "    float4 q_self = g_QField[dispatchThreadID];\n";
        ss << "    float3 v_self = g_VField[dispatchThreadID].xyz;\n\n";

        ss << "    // 1. Spatial Difference: Curl(V)\n";
        ss << "    float3 v_px = g_VField[dispatchThreadID + uint3(1,0,0)].xyz;\n";
        ss << "    float3 v_nx = g_VField[dispatchThreadID - uint3(1,0,0)].xyz;\n";
        ss << "    float3 v_py = g_VField[dispatchThreadID + uint3(0,1,0)].xyz;\n";
        ss << "    float3 v_ny = g_VField[dispatchThreadID - uint3(0,1,0)].xyz;\n";
        ss << "    float3 v_pz = g_VField[dispatchThreadID + uint3(0,0,1)].xyz;\n";
        ss << "    float3 v_nz = g_VField[dispatchThreadID - uint3(0,0,1)].xyz;\n";
        ss << "    float3 curl_v = float3(\n";
        ss << "        (v_py.z - v_ny.z) - (v_pz.y - v_nz.y),\n";
        ss << "        (v_pz.x - v_nz.x) - (v_px.z - v_nx.z),\n";
        ss << "        (v_px.y - v_nx.y) - (v_py.x - v_ny.x)\n";
        ss << "    ) * 0.5f;\n\n";

        ss << "    // 2. Phase-Locking Torque\n";
        ss << "    float3 sync_torque = float3(0, 0, 0);\n";
        ss << "    int3 offsets[6] = { int3(1,0,0), int3(-1,0,0), int3(0,1,0), int3(0,-1,0), int3(0,0,1), int3(0,0,-1) };\n";
        ss << "    [unroll]\n";
        ss << "    for (int i = 0; i < 6; i++) {\n";
        ss << "        uint3 neighborCoord = clamp(dispatchThreadID + offsets[i], uint3(0,0,0), g_GridSize - 1);\n";
        ss << "        float4 q_neighbor = g_QField[neighborCoord];\n";
        ss << "        float4 q_rel = quat_mul(q_neighbor, quat_conj(q_self));\n";
        ss << "        sync_torque += q_rel.xyz;\n";
        ss << "    }\n";
        ss << "    sync_torque *= K_0;\n\n";

        ss << "    // 3. Thermal Noise & Stochastic Integration\n";
        ss << "    float noiseSeed = dot(dispatchThreadID, uint3(1, 149, 311)) + dt;\n";
        ss << "    float3 thermal_noise = float3(\n";
        ss << "        frac(sin(noiseSeed) * 43758.5453) - 0.5f,\n";
        ss << "        frac(sin(noiseSeed + 1.0) * 24614.63) - 0.5f,\n";
        ss << "        frac(sin(noiseSeed + 2.0) * 56445.12) - 0.5f\n";
        ss << "    ) * sqrt(2.0f * temp * dt);\n\n";

        ss << "    float3 total_torque = curl_v + sync_torque + thermal_noise;\n";
        ss << "    float torque_len = length(total_torque) + 1e-6f;\n";
        ss << "    float half_angle = torque_len * dt * 0.5f;\n";
        ss << "    float4 dq = float4((total_torque / torque_len) * sin(half_angle), cos(half_angle));\n";
        ss << "    float4 q_next = normalize(quat_mul(dq, q_self));\n\n";

        ss << "    // 4. Local Coherence & Zero-Branch Blending\n";
        ss << "    float phi = saturate(length(sync_torque) / (K_0 * 6.0f + 1e-5f));\n";
        ss << "    float w_solid = saturate((phi - 0.7f) * 10.0f);\n";
        ss << "    float w_gas   = saturate((0.3f - phi) * 10.0f);\n";
        ss << "    float w_fluid = 1.0f - w_solid - w_gas;\n\n";

        ss << "    float3 accel = (w_fluid * sync_torque - w_gas * float3(temp, temp, temp)) * dt;\n";
        ss << "    float3 v_next = v_self + accel;\n\n";

        ss << "    g_QField[dispatchThreadID] = q_next;\n";
        ss << "    g_VField[dispatchThreadID] = float4(v_next, 0.0f);\n";
        ss << "}\n";

        return ss.str();
    }
};

} // namespace elysia::topir::codegen

#endif // HLSL_CODEGEN_HPP
