r"""
Central Metacognitive Workspace (중앙 메타인지 사고 공간)
========================================================================

Implements the Central Metacognitive Workspace (CMW) that combines symbol/logos
topology and raw sensory tensors into a unified grounding manifold, performs
qualitative discrepancy reasoning (WHAT, HOW MUCH, HOW), reflects metacognitively
on internal symbol validity, and evolves schema topology (symbol differentiation,
causal mediator insertion, phase re-anchoring).

Key Components:
1. GroundingManifold ($\mathcal{M}_G$):
   Combines symbol topology vectors and raw sensory tensors into unified grounding space.
2. QualitativeDiscrepancyEngine ($\mathcal{Q}_{Diff}$):
   Reasons about qualitative discrepancies:
   - WHAT: Which symbol/causal origin is misaligned.
   - HOW MUCH: Numerical magnitude of topological strain.
   - HOW: Causal type ('LENS_MISALIGNMENT', 'CONTEXT_SHIFT', or 'STRUCTURAL_GAP').
3. MetacognitiveReflectionLoop ($\mathcal{M}_{Reflect}$):
   Reflects on symbol validity, computes void gradients ($\nabla V_{void}$), and drives active exploration value.
4. SchemaTopologyRewiringUnit ($\mathcal{S}_{Evol}$):
   Dynamically splits symbols (differentiation), inserts causal mediators, and re-anchors phase coordinates.
"""

from dataclasses import dataclass, field
import math
import time
from typing import Any, Dict, List, Optional, Tuple, Union
import numpy as np


@dataclass
class QualitativeDiffReport:
    """Report generated by Qualitative Discrepancy Engine."""
    what_symbol_id: str
    how_much_magnitude: float
    how_causal_type: str  # 'LENS_MISALIGNMENT', 'CONTEXT_SHIFT', 'STRUCTURAL_GAP'
    discrepancy_vector: np.ndarray
    reasoning_summary: str


@dataclass
class SchemaEvolutionAction:
    """Action taken by Schema Topology Rewiring Unit."""
    action_type: str  # 'SYMBOL_DIFFERENTIATION', 'CAUSAL_INSERTION', 'PHASE_REANCHORING', 'FINE_TUNING'
    target_symbol: str
    new_symbols_created: List[str]
    description: str


class GroundingManifold:
    """
    Symbol-Sensory Grounding Manifold ($\mathcal{M}_G$).
    Binds symbol/logos topology vectors and raw sensory wave tensors into unified manifold coordinates.
    """
    def __init__(self, dim: int = 16):
        self.dim = dim

    def ground(self, symbol_vec: np.ndarray, sensory_wave: np.ndarray) -> np.ndarray:
        s_vec = np.asarray(symbol_vec, dtype=np.float32).flatten()
        w_vec = np.asarray(sensory_wave, dtype=np.float32).flatten()

        # Pad or slice to dim
        if len(s_vec) < self.dim:
            s_vec = np.pad(s_vec, (0, self.dim - len(s_vec)))
        else:
            s_vec = s_vec[: self.dim]

        if len(w_vec) < self.dim:
            w_vec = np.pad(w_vec, (0, self.dim - len(w_vec)))
        else:
            w_vec = w_vec[: self.dim]

        # Clifford wedge-like cross product / tensor coupling
        grounded = s_vec * np.roll(w_vec, 1) + w_vec * np.roll(s_vec, 1)
        norm = np.linalg.norm(grounded) + 1e-8
        return grounded / norm


class QualitativeDiscrepancyEngine:
    """
    Qualitative Discrepancy Engine ($\mathcal{Q}_{Diff}$).
    Reasons about qualitative differences:
    - WHAT: Which symbol node in the symbol bank has maximum divergence.
    - HOW MUCH: Strain magnitude.
    - HOW: Categorizes discrepancy into LENS_MISALIGNMENT, CONTEXT_SHIFT, or STRUCTURAL_GAP.
    """
    def __init__(self, dim: int = 16, num_symbols: int = 8):
        self.dim = dim
        self.num_symbols = num_symbols
        # Symbol Bank representations
        np.random.seed(42)
        self.symbol_bank = {
            f"SYMBOL_NODE_{i}": np.random.randn(dim).astype(np.float32)
            for i in range(num_symbols)
        }

    def reason_discrepancy(self, internal_manifold: np.ndarray, world_response: np.ndarray) -> QualitativeDiffReport:
        int_m = np.asarray(internal_manifold, dtype=np.float32).flatten()
        w_res = np.asarray(world_response, dtype=np.float32).flatten()

        if len(int_m) < self.dim:
            int_m = np.pad(int_m, (0, self.dim - len(int_m)))
        else:
            int_m = int_m[: self.dim]

        if len(w_res) < self.dim:
            w_res = np.pad(w_res, (0, self.dim - len(w_res)))
        else:
            w_res = w_res[: self.dim]

        diff_vec = int_m - w_res
        magnitude = float(np.linalg.norm(diff_vec))

        # WHAT: find closest symbol node in bank to discrepancy vector
        best_symbol = "SYMBOL_NODE_0"
        max_dot = -1e9
        for sym_id, sym_vec in self.symbol_bank.items():
            dot_val = float(np.dot(diff_vec, sym_vec))
            if dot_val > max_dot:
                max_dot = dot_val
                best_symbol = sym_id

        # HOW: determine causal type based on directional variance and magnitude
        if magnitude < 0.3:
            how_type = "LENS_MISALIGNMENT"
            summary = "Minor phase discrepancy; requires observation lens angle adjustment."
        elif magnitude < 0.7:
            how_type = "CONTEXT_SHIFT"
            summary = "Moderate contextual shift detected; requires phase re-anchoring and mediator update."
        else:
            how_type = "STRUCTURAL_GAP"
            summary = "Severe structural gap / void detected; requires symbol differentiation and topology rewiring."

        return QualitativeDiffReport(
            what_symbol_id=best_symbol,
            how_much_magnitude=magnitude,
            how_causal_type=how_type,
            discrepancy_vector=diff_vec,
            reasoning_summary=summary,
        )


class MetacognitiveReflectionLoop:
    """
    Metacognitive Self-Evaluation Loop ($\mathcal{M}_{Reflect}$).
    Reflects on symbol validity, tracks symbol confidence scores,
    and computes void gradients ($\nabla V_{void}$) to drive active seeking value.
    """
    def __init__(self, dim: int = 16):
        self.dim = dim
        self.symbol_validity_scores: Dict[str, float] = {}

    def reflect(self, report: QualitativeDiffReport) -> Dict[str, Any]:
        sym_id = report.what_symbol_id
        current_validity = self.symbol_validity_scores.get(sym_id, 1.0)

        # Validity degrades proportional to strain magnitude
        degradation = 0.2 * report.how_much_magnitude
        new_validity = max(0.0, current_validity - degradation)
        self.symbol_validity_scores[sym_id] = new_validity

        # Compute void gradient magnitude driving exploration
        void_gradient_mag = (1.0 - new_validity) * report.how_much_magnitude
        active_seeking_value = float(np.tanh(void_gradient_mag * 2.0))

        return {
            "target_symbol": sym_id,
            "updated_validity": new_validity,
            "void_gradient_magnitude": void_gradient_mag,
            "active_seeking_value": active_seeking_value,
            "is_ignorant": new_validity < 0.4,
        }


class SchemaTopologyRewiringUnit:
    """
    Schema Topology Rewiring Unit ($\mathcal{S}_{Evol}$).
    Executes structural adaptations based on qualitative reasoning:
    - Symbol Differentiation: Splits a strained symbol node into sub-nodes ($S_0 \to S_{0a}, S_{0b}$).
    - Causal Insertion: Inserts intermediate mediator nodes in causal chains.
    - Phase Re-anchoring: Rotates lens angles to align with world frequencies.
    """
    def __init__(self, discrepancy_engine: QualitativeDiscrepancyEngine):
        self.discrepancy_engine = discrepancy_engine
        self.evolution_history: List[SchemaEvolutionAction] = []

    def evolve_schema(self, report: QualitativeDiffReport, reflect_data: Dict[str, Any]) -> SchemaEvolutionAction:
        sym_id = report.what_symbol_id
        how_type = report.how_causal_type
        mag = report.how_much_magnitude

        if how_type == "STRUCTURAL_GAP" and reflect_data["is_ignorant"]:
            # Symbol Differentiation
            new_a = f"{sym_id}_ALPHA"
            new_b = f"{sym_id}_BETA"
            orig_vec = self.discrepancy_engine.symbol_bank[sym_id]
            self.discrepancy_engine.symbol_bank[new_a] = orig_vec + np.random.randn(self.discrepancy_engine.dim) * 0.1
            self.discrepancy_engine.symbol_bank[new_b] = orig_vec - np.random.randn(self.discrepancy_engine.dim) * 0.1

            action = SchemaEvolutionAction(
                action_type="SYMBOL_DIFFERENTIATION",
                target_symbol=sym_id,
                new_symbols_created=[new_a, new_b],
                description=f"Differentiated strained symbol {sym_id} into {new_a} and {new_b} due to structural gap.",
            )

        elif how_type == "CONTEXT_SHIFT":
            # Causal Mediator Insertion
            mediator = f"{sym_id}_MEDIATOR"
            self.discrepancy_engine.symbol_bank[mediator] = report.discrepancy_vector.copy()

            action = SchemaEvolutionAction(
                action_type="CAUSAL_INSERTION",
                target_symbol=sym_id,
                new_symbols_created=[mediator],
                description=f"Inserted causal mediator node {mediator} to bridge contextual shift.",
            )

        elif how_type == "LENS_MISALIGNMENT":
            # Phase Re-anchoring
            action = SchemaEvolutionAction(
                action_type="PHASE_REANCHORING",
                target_symbol=sym_id,
                new_symbols_created=[],
                description=f"Re-anchored phase coordinates for {sym_id} to eliminate minor lens mismatch.",
            )

        else:
            action = SchemaEvolutionAction(
                action_type="FINE_TUNING",
                target_symbol=sym_id,
                new_symbols_created=[],
                description=f"Fine-tuned weights for {sym_id}.",
            )

        self.evolution_history.append(action)
        return action


class CentralMetacognitiveWorkspace:
    """
    [Central Metacognitive Workspace Engine Core]
    Integrates Grounding Manifold, Qualitative Discrepancy Engine,
    Metacognitive Reflection Loop, and Schema Topology Rewiring Unit.
    """
    def __init__(self, dim: int = 16, num_symbols: int = 8):
        self.dim = dim
        self.grounding_manifold = GroundingManifold(dim=dim)
        self.discrepancy_engine = QualitativeDiscrepancyEngine(dim=dim, num_symbols=num_symbols)
        self.reflection_loop = MetacognitiveReflectionLoop(dim=dim)
        self.rewiring_unit = SchemaTopologyRewiringUnit(self.discrepancy_engine)

    def process_cognition(
        self,
        symbol_vec: np.ndarray,
        sensory_wave: np.ndarray,
        world_response: np.ndarray,
    ) -> Dict[str, Any]:
        """
        Main cognitive reasoning cycle:
        1. Symbol-Sensory Grounding ($\mathcal{M}_G$)
        2. Qualitative Discrepancy Reasoning ($\mathcal{Q}_{Diff}$)
        3. Metacognitive Reflection ($\mathcal{M}_{Reflect}$)
        4. Schema Topology Rewiring & Symbol Evolution ($\mathcal{S}_{Evol}$)
        """
        # 1. Grounding
        grounded_manifold = self.grounding_manifold.ground(symbol_vec, sensory_wave)

        # 2. Qualitative Discrepancy Reasoning
        diff_report = self.discrepancy_engine.reason_discrepancy(grounded_manifold, world_response)

        # 3. Metacognitive Reflection
        reflect_data = self.reflection_loop.reflect(diff_report)

        # 4. Schema Rewiring & Evolution
        evolution_action = self.rewiring_unit.evolve_schema(diff_report, reflect_data)

        return {
            "grounded_manifold": grounded_manifold,
            "discrepancy_report": diff_report,
            "reflection_data": reflect_data,
            "evolution_action": evolution_action,
        }
