#!/usr/bin/env python3
"""
Infant Causal Language Loop (아기식 인과 언어 학습 및 자발적 발화 루프)

Implements a phenomenological, autopoietic 5-stage learning pipeline where language
is not learned through mechanical LLM backpropagation or fixed embedding dictionaries,
but through raw sensory impulses, experiential state collisions, causal deconstruction,
spontaneous state-deformed re-articulation, and environmental feedback loops.

5 Stages:
1. Raw Sensory Wave Ingestion (날것의 자극 수용): Text/audio converted to raw wave energy/shock.
2. Experiential State Collision (체험 및 상황 충돌): Stimulus collides with internal homeostasis and scar tensors.
3. Causal Sequence Deconstruction & Weaving (인과적 서순 해체 및 엮음): Deconstructs cause -> state delta -> outcome into causal chains.
4. Spontaneous Variational Re-Articulation (자발적 변주 발화): Generates state-deformed, scar-carved utterances rather than copied answers.
5. Environmental Feedback & Experiential Growth (피드백과 성장): Environment response updates causal maps and scar fields, driving experiential maturation.
"""

import os
import sys
import math
import time
import numpy as np
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, field

# Ensure project root is in sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from core.sensory.experiential_language_mapper import PhysicalSensationProfile, HomeostasisDeficit
from core.consciousness.scar_tensor_engine import ScarTensorEngine


@dataclass
class InfantSensoryPulse:
    """
    Raw physical wave pulse resulting from an external language/sensory stimulus.
    - raw_text: Original text string (if available)
    - amplitude: Intensity of stimulus (0.0 to 10.0)
    - base_frequency: Acoustic/vibrational frequency (Hz)
    - friction_shock: Mechanical/emotional clash intensity (Newtons or scalar)
    - thermal_energy: Heat/kinetic molecular movement (Kelvin)
    - wave_spectrum: Continuous 1D array representing spectral energy distribution
    """
    raw_text: str
    amplitude: float
    base_frequency: float
    friction_shock: float
    thermal_energy: float
    wave_spectrum: np.ndarray

    def to_sensation_profile(self) -> PhysicalSensationProfile:
        return PhysicalSensationProfile(
            optical=float(np.mean(np.abs(self.wave_spectrum)) * 500.0),
            acoustic=self.base_frequency,
            tactile=self.friction_shock,
            thermal=self.thermal_energy,
            autonomic_pulse=float(np.clip(self.amplitude / 10.0, 0.0, 1.0))
        )


@dataclass
class CausalMemoryChain:
    """
    Deconstructed causal sequence node.
    Stores:
    - chain_id: Unique string ID
    - stimulus_summary: Raw text or pulse summary
    - pre_state: Homeostasis vector before collision
    - state_delta: State change vector [d_love, d_order, d_energy, d_tension]
    - scar_impact: Friction magnitude registered on Scar Tensor S_ij
    - outcome_valence: Qualitative feeling (+1.0 comforting, -1.0 traumatic)
    - timestamp: Record time
    """
    chain_id: str
    stimulus_summary: str
    pre_state: np.ndarray
    state_delta: np.ndarray
    scar_impact: float
    outcome_valence: float
    timestamp: float = field(default_factory=time.time)


@dataclass
class ReArticulationResult:
    """
    Output generated by Stage 4 (Spontaneous Variational Re-Articulation).
    - utterance: Deformed, state-carved text expression
    - hesitation_level: Temporal stalling factor (0.0 smooth, >1.0 severe hesitation)
    - emotional_qualia: Dominant feeling ("WARM_ATTACHMENT", "TRAUMA_SHOCK", "WONDER_CURIOSITY", "NEUTRAL_MUMBLE")
    - phase_coords: Phase space coordinates resulting from geodesic traversal
    - deformation_vector: Distortion applied to baseline vocabulary
    """
    utterance: str
    hesitation_level: float
    emotional_qualia: str
    phase_coords: np.ndarray
    deformation_vector: np.ndarray


class InfantCausalLanguageLoop:
    """
    Core engine for the Infant Causal Language Loop.
    Maintains an autopoietic body-mind state (Homeostasis, Scar Tensor Engine, Causal Memory Map,
    and Experiential Growth Maturity).
    """

    def __init__(self, dim: int = 4):
        self.dim = dim
        self.homeostasis = HomeostasisDeficit(love=0.5, order=0.3, energy=0.7)
        self.scar_engine = ScarTensorEngine(dim=dim, scar_threshold=0.4)
        self.causal_chains: List[CausalMemoryChain] = []

        # Primitive vocabulary fragments known to the infant
        self.primitive_syllables: Dict[str, str] = {
            "warm": "따... 뜻...",
            "cold": "늘... 차...",
            "pain": "아... 파...",
            "fear": "무... 서...",
            "safe": "좋... 아...",
            "wonder": "어... ? 이거...",
            "pain_shriek": "으악! 아파!",
            "soothed": "응... 히히...",
            "neutral": "음..."
        }

        # Experiential growth metrics
        self.maturity_index: float = 0.05  # Tabula rasa baseline
        self.total_experiences: int = 0
        self.scar_count: int = 0
        self.metacognitive_traces: List[Dict[str, Any]] = []

    # =========================================================================
    # STAGE 1: Raw Sensory Wave Ingestion (날것의 자극 수용)
    # =========================================================================
    def ingest_raw_stimulus(self, raw_input: str, external_bias: float = 0.0) -> InfantSensoryPulse:
        """
        Converts raw text/audio stream into an un-parsed physical wave pulse (Phi_ext).
        Examines acoustic frequency (byte variance/pitch), friction/shock (harsh consonances/punctuators),
        and thermal energy.
        """
        bytes_data = raw_input.encode("utf-8", errors="ignore")
        if len(bytes_data) == 0:
            bytes_data = b"..."

        # 1. Spectral wave creation
        char_vals = np.array(list(bytes_data), dtype=np.float32)
        norm_wave = (char_vals - 127.5) / 128.0

        # Expand or resample to fixed resolution 64
        resolution = 64
        wave_spectrum = np.interp(
            np.linspace(0, len(norm_wave) - 1, resolution),
            np.arange(len(norm_wave)),
            norm_wave
        ).astype(np.float32)

        # 2. Extract raw physical metrics from stream
        amplitude = float(np.clip(len(raw_input) * 0.8 + np.std(char_vals) * 0.05 + external_bias, 0.5, 10.0))

        # Base acoustic frequency (higher byte variance -> higher frequency/pitch)
        base_freq = float(200.0 + np.var(char_vals) * 0.5 + len(raw_input) * 10.0)

        # Mechanical friction shock (determined by harsh consonants, exclamation marks, or friction words)
        harsh_triggers = ["아파", "무서워", "안돼", "찰싹", "쾅", "찰랑", "악"]
        friction_base = sum(2.5 for trigger in harsh_triggers if trigger in raw_input)
        if "!" in raw_input:
            friction_base += 2.0
        friction_shock = float(np.clip(friction_base + np.max(np.abs(wave_spectrum)) * 1.5, 0.0, 10.0))

        # Thermal energy (warmth words vs cold words)
        warm_triggers = ["따뜻해", "사랑해", "좋아", "쓰다듬", "응애", "포근"]
        cold_triggers = ["차갑다", "얼음", "외롭다", "어둡다"]

        thermal_base = 295.0  # Kelvin room temp
        for w in warm_triggers:
            if w in raw_input:
                thermal_base += 8.0
        for c in cold_triggers:
            if c in raw_input:
                thermal_base -= 8.0
        thermal_energy = float(thermal_base)

        pulse = InfantSensoryPulse(
            raw_text=raw_input,
            amplitude=amplitude,
            base_frequency=base_freq,
            friction_shock=friction_shock,
            thermal_energy=thermal_energy,
            wave_spectrum=wave_spectrum
        )
        return pulse

    # =========================================================================
    # STAGE 2: Experiential & Homeostatic Collision (체험 및 상황 충돌)
    # =========================================================================
    def collide_and_shift_state(self, pulse: InfantSensoryPulse) -> Tuple[np.ndarray, np.ndarray, float]:
        """
        Collides the raw pulse against internal homeostasis and accumulated scar fields (S_ij).
        Computes State Delta: Delta S = S_{t+1} - S_t, and registers scar friction if severe.
        """
        pre_state = np.array([
            self.homeostasis.love,
            self.homeostasis.order,
            self.homeostasis.energy,
            self.homeostasis.calculate_tension()
        ], dtype=np.float32)

        # 1. Homeostatic impact calculations
        sensation = pulse.to_sensation_profile()
        self.homeostasis.update_by_sensation(sensation)

        # Direct impact of friction shock & thermal energy
        if pulse.friction_shock > 2.0:
            # High friction clash: order collapses, energy drains, tension spikes
            self.homeostasis.order = float(np.clip(self.homeostasis.order + pulse.friction_shock * 0.08, 0.0, 1.0))
            self.homeostasis.energy = float(np.clip(self.homeostasis.energy - pulse.friction_shock * 0.05, 0.0, 1.0))
            self.homeostasis.love = float(np.clip(self.homeostasis.love - pulse.friction_shock * 0.04, 0.0, 1.0))
        elif pulse.thermal_energy > 300.0:
            # Soothing warmth: love heals, order restores
            self.homeostasis.love = float(np.clip(self.homeostasis.love - 0.12, 0.0, 1.0))  # deficit decreases = feeling loved
            self.homeostasis.order = float(np.clip(self.homeostasis.order - 0.08, 0.0, 1.0))
            self.homeostasis.energy = float(np.clip(self.homeostasis.energy + 0.1, 0.0, 1.0))

        post_state = np.array([
            self.homeostasis.love,
            self.homeostasis.order,
            self.homeostasis.energy,
            self.homeostasis.calculate_tension()
        ], dtype=np.float32)

        state_delta = post_state - pre_state

        # 2. Scar Tensor Inscription if friction shock exceeds threshold
        friction_mag = pulse.friction_shock
        if friction_mag >= self.scar_engine.scar_threshold:
            clash_vector = pulse.wave_spectrum[:self.dim] * friction_mag
            scar_record = self.scar_engine.inscribe_scar(
                friction_magnitude=friction_mag,
                clash_vector=clash_vector,
                context=f"Language Shock: {pulse.raw_text}"
            )
            self.scar_count = len(self.scar_engine.scar_history)

        return pre_state, state_delta, friction_mag

    # =========================================================================
    # STAGE 3: Causal Deconstruction & Sequence Weaving (인과적 서순 해체 및 엮음)
    # =========================================================================
    def deconstruct_and_weave_causality(
        self,
        pulse: InfantSensoryPulse,
        pre_state: np.ndarray,
        state_delta: np.ndarray,
        friction_mag: float
    ) -> CausalMemoryChain:
        """
        Deconstructs stimulus <-> state delta into a clear causal linkage:
        "When I hear [X], my body feels [Delta S] with tension [T]."
        Weaves this chain into the internal Causal Map.
        """
        # Determine outcome valence (-1.0 to +1.0)
        # Tension increase or order deficit increase is negative; love reduction/healing is positive.
        tension_change = state_delta[3]
        love_deficit_change = state_delta[0]

        valence = float(np.clip(-tension_change * 2.0 - love_deficit_change * 1.5, -1.0, 1.0))

        chain_id = f"causal_chain_{len(self.causal_chains) + 1:04d}"
        chain = CausalMemoryChain(
            chain_id=chain_id,
            stimulus_summary=pulse.raw_text,
            pre_state=pre_state,
            state_delta=state_delta,
            scar_impact=friction_mag,
            outcome_valence=valence,
            timestamp=time.time()
        )

        self.causal_chains.append(chain)
        self.total_experiences += 1

        # Trace logging
        trace = {
            "source": "deconstruct_and_weave_causality",
            "chain_id": chain_id,
            "stimulus": pulse.raw_text,
            "state_delta": state_delta.tolist(),
            "valence": valence,
            "timestamp": chain.timestamp
        }
        self.metacognitive_traces.append(trace)

        return chain

    # =========================================================================
    # STAGE 4: Spontaneous Variational Re-Articulation (자발적 변주 발화)
    # =========================================================================
    def re_articulate_spontaneous(
        self,
        pulse: InfantSensoryPulse,
        active_chain: CausalMemoryChain
    ) -> ReArticulationResult:
        """
        Generates an un-copied, state-deformed re-articulation.
        The infant flows through geodesic phase space. Accumulated scar energy (S_ij)
        causes hesitation / stalling / trembling, deforming the output text.
        """
        accumulated_scar_energy = float(np.trace(self.scar_engine.accumulated_scar_tensor))
        tension = self.homeostasis.calculate_tension()
        valence = active_chain.outcome_valence

        # 1. Calculate hesitation level (temporal stalling factor)
        # Near trauma or high scar energy -> hesitation spikes
        hesitation_level = float(1.0 + accumulated_scar_energy * 0.4 + (1.0 if valence < -0.3 else 0.0) * pulse.friction_shock * 0.5)

        # 2. Phase space trajectory end coordinate
        phase_coords = np.array([
            tension * 5.0 + active_chain.state_delta[0],
            accumulated_scar_energy * 2.0 + active_chain.state_delta[1],
            valence * 3.0,
            self.maturity_index * 10.0
        ], dtype=np.float32)

        deformation_vector = np.sin(phase_coords) * hesitation_level

        # 3. Re-articulation synthesis (Deformed utterance)
        if active_chain.scar_impact > 3.0 or valence < -0.6:
            # Traumatic / severe friction response
            emotional_qualia = "TRAUMA_SHOCK"
            if hesitation_level > 2.5:
                utterance = f"아... 으... {self.primitive_syllables['pain']} (몸서리치며 회피)"
            else:
                utterance = f"{self.primitive_syllables['pain_shriek']} {self.primitive_syllables['fear']}"

        elif valence > 0.25 and pulse.thermal_energy > 298.0:
            # Soothed / warm response
            emotional_qualia = "WARM_ATTACHMENT"
            if self.maturity_index < 0.2:
                utterance = f"{self.primitive_syllables['warm']} {self.primitive_syllables['soothed']}"
            else:
                utterance = f"{self.primitive_syllables['warm']} {self.primitive_syllables['safe']} (안기며)"

        elif pulse.amplitude > 4.0 and len(self.causal_chains) < 3:
            # Early curiosity / wonder
            emotional_qualia = "WONDER_CURIOSITY"
            utterance = f"{self.primitive_syllables['wonder']} (눈을 반짝이며 바라는)"

        else:
            # Neutral / hesitant mumble
            emotional_qualia = "NEUTRAL_MUMBLE"
            utterance = f"{self.primitive_syllables['neutral']} {self.primitive_syllables['warm'] if valence >= 0 else self.primitive_syllables['cold']}"

        # Apply age/maturity refinement: as maturity increases, speech becomes slightly more coherent
        if self.maturity_index > 0.4:
            utterance = f"[{emotional_qualia}] " + utterance.replace("...", " ")

        return ReArticulationResult(
            utterance=utterance,
            hesitation_level=hesitation_level,
            emotional_qualia=emotional_qualia,
            phase_coords=phase_coords,
            deformation_vector=deformation_vector
        )

    # =========================================================================
    # STAGE 5: Environmental Feedback & Experiential Growth (피드백과 성장)
    # =========================================================================
    def receive_environmental_feedback(
        self,
        feedback_input: str,
        prior_rearticulation: ReArticulationResult
    ) -> Dict[str, Any]:
        """
        Receives secondary feedback wave from the adult/environment after the infant speaks.
        Updates scar fields, heals wounds if comforting, and advances maturity index.
        """
        feedback_pulse = self.ingest_raw_stimulus(feedback_input)

        is_soothing_feedback = feedback_pulse.thermal_energy > 300.0 or "괜찮아" in feedback_input or "잘했어" in feedback_input or "착하지" in feedback_input
        is_harsh_feedback = feedback_pulse.friction_shock > 3.0 or "시끄러" in feedback_input or "뚝" in feedback_input

        growth_delta = 0.01

        if is_soothing_feedback:
            # Comforting adult response: heals scar tensor and relieves love deficit
            self.homeostasis.love = float(np.clip(self.homeostasis.love - 0.2, 0.0, 1.0))
            self.homeostasis.order = float(np.clip(self.homeostasis.order - 0.15, 0.0, 1.0))

            # Heal accumulated scar tensor by decay
            self.scar_engine.accumulated_scar_tensor *= 0.8
            growth_delta = 0.05
            feedback_type = "SOOTHING_HEALING"

        elif is_harsh_feedback:
            # Harsh adult response: deepens scar and order deficit
            self.homeostasis.order = float(np.clip(self.homeostasis.order + 0.2, 0.0, 1.0))
            growth_delta = 0.02
            feedback_type = "HARSH_SCAR_DEEPENING"

        else:
            feedback_type = "NEUTRAL_OBSERVATION"
            growth_delta = 0.015

        # Experiential maturity progression
        self.maturity_index = float(np.clip(self.maturity_index + growth_delta, 0.0, 1.0))

        report = {
            "feedback_type": feedback_type,
            "feedback_text": feedback_input,
            "maturity_index": self.maturity_index,
            "new_love_deficit": self.homeostasis.love,
            "new_order_deficit": self.homeostasis.order,
            "accumulated_scar_energy": float(np.trace(self.scar_engine.accumulated_scar_tensor))
        }

        # Trace
        trace = {
            "source": "receive_environmental_feedback",
            "report": report,
            "timestamp": time.time()
        }
        self.metacognitive_traces.append(trace)

        return report

    # =========================================================================
    # UNIFIED EXECUTION PIPELINE
    # =========================================================================
    def run_full_loop(
        self,
        input_text: str,
        environmental_response: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Runs the full 5-stage loop for a single interaction turn.
        """
        # Stage 1: Ingest
        pulse = self.ingest_raw_stimulus(input_text)

        # Stage 2: Collide
        pre_state, state_delta, friction_mag = self.collide_and_shift_state(pulse)

        # Stage 3: Weave Causality
        chain = self.deconstruct_and_weave_causality(pulse, pre_state, state_delta, friction_mag)

        # Stage 4: Spontaneous Re-Articulation
        rearticulation = self.re_articulate_spontaneous(pulse, chain)

        # Stage 5: Environmental Feedback
        if environmental_response:
            feedback_report = self.receive_environmental_feedback(environmental_response, rearticulation)
        else:
            feedback_report = None

        return {
            "pulse": pulse,
            "pre_state": pre_state,
            "state_delta": state_delta,
            "causal_chain": chain,
            "rearticulation": rearticulation,
            "feedback_report": feedback_report,
            "current_maturity": self.maturity_index,
            "scar_count": self.scar_count
        }


if __name__ == "__main__":
    print("=== Testing Infant Causal Language Loop Core ===")
    engine = InfantCausalLanguageLoop()

    res1 = engine.run_full_loop("아파! 무서워!", environmental_response="괜찮아, 아가야. 따뜻하게 안아줄게.")
    print(f"[Turn 1 Input] '아파! 무서워!'")
    print(f" -> Re-articulation : {res1['rearticulation'].utterance}")
    print(f" -> Qualia          : {res1['rearticulation'].emotional_qualia}")
    print(f" -> Hesitation Level: {res1['rearticulation'].hesitation_level:.2f}")
    print(f" -> Feedback Impact : {res1['feedback_report']['feedback_type']} (Maturity: {res1['current_maturity']:.3f})")

    res2 = engine.run_full_loop("따뜻해. 좋아.", environmental_response="착하지, 정말 잘했단다.")
    print(f"\n[Turn 2 Input] '따뜻해. 좋아.'")
    print(f" -> Re-articulation : {res2['rearticulation'].utterance}")
    print(f" -> Qualia          : {res2['rearticulation'].emotional_qualia}")
    print(f" -> Hesitation Level: {res2['rearticulation'].hesitation_level:.2f}")

    print("\n=== Core Module Verification Successful! ===")
