"""
NaturalSelection (        )
================================

"The filter of time. The audit of survival."
"      .       ."

This module audits the 'spores' (mutations) generated by the QuantumBioEngine.
It selects the most resonant logic to be grafted into the permanent core.
"""

import logging
import os
import importlib.util
import shutil
from typing import List

logger = logging.getLogger("Elysia.Life.NaturalSelection")

class NaturalSelection:
    def __init__(self, bio_path: str = "Core/L8_Life"):
        self.bio_path = bio_path
        self.archive_path = os.path.join(bio_path, "Archive")
        os.makedirs(self.archive_path, exist_ok=True)
        
        logger.info("  NaturalSelection Audit Engine Online.")

    def audit_spores(self):
        """
        Scans all spores in L8 and evaluates their 'resonance'.
        """
        files = [f for f in os.listdir(self.bio_path) if f.startswith("spore_") and f.endswith(".py")]
        
        if not files:
            logger.debug("  No spores found for auditing.")
            return

        logger.info(f"  Auditing {len(files)} genetic variations...")
        
        for filename in files:
            filepath = os.path.join(self.bio_path, filename)
            resonance = self._evaluate_spore(filepath)
            
            if resonance > 1.05: # Beneficial mutation
                logger.info(f"  BENEFICIAL: Resonant spore found: {filename} (Resonance: {resonance:.4f})")
                self._graft_to_core(filepath)
            else:
                logger.info(f"  NEUTRAL/WEAK: Archiving spore: {filename} (Resonance: {resonance:.4f})")
                self._archive_spore(filepath)

    def _evaluate_spore(self, filepath: str) -> float:
        """
        Simulates the spore's effect.
        In this initial version, it simply calculates a pseudo-resonance score.
        """
        try:
            spec = importlib.util.spec_from_file_location("spore_mod", filepath)
            spore_mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(spore_mod)
            
            if hasattr(spore_mod, 'effect_on_pulse'):
                # Test with a base resonance of 1.0
                return spore_mod.effect_on_pulse(1.0)
        except Exception as e:
            logger.error(f"Error evaluating spore {filepath}: {e}")
        return 0.0

    def _graft_to_core(self, filepath: str):
        """
        Grafts the beneficiary logic into a permanent 'Stable' repository.
        (Future: Will actually modify Core files)
        """
        target_path = os.path.join(self.bio_path, "STABLE_DNA.py")
        # For now, just append as a comment to simulate the grafting
        with open(filepath, 'r', encoding='utf-8') as src:
            content = src.read()
        
        with open(target_path, 'a', encoding='utf-8') as dst:
            dst.write(f"\n# --- Grafted Growth ({os.path.basename(filepath)}) ---\n")
            dst.write(content)
            
        logger.info(f"  [GRAFT] Logic from {os.path.basename(filepath)} has been merged into STABLE_DNA.py")
        self._archive_spore(filepath)

    def _archive_spore(self, filepath: str):
        shutil.move(filepath, os.path.join(self.archive_path, os.path.basename(filepath)))

if __name__ == "__main__":
    audit = NaturalSelection()
    audit.audit_spores()
