import numpy as np
from typing import List, Dict, Any, Tuple, Optional
from .phase_space_node import PhaseSpaceNode

class OpenValenceField:
    """
    [Open Valence Field Architecture (+@)]
    Simulates continuous causal potential fields generated by open (+@) latent valence vectors.
    Computes interference superposition, causal tension gradients (-∇U_latent),
    phase space dynamic trajectory updates, and dynamic node instantiation (spawning)
    when field tension exceeds the rupture threshold (τ_rupture).
    """

    def __init__(self, rupture_threshold: float = 3.5, max_nodes: int = 100):
        self.nodes: Dict[int, PhaseSpaceNode] = {}
        self.rupture_threshold = rupture_threshold
        self.max_nodes = max_nodes
        self._next_node_id = 0
        self.spawn_history: List[Dict[str, Any]] = []

    def add_node(self, node: PhaseSpaceNode) -> int:
        if node.node_id in self.nodes:
            raise ValueError(f"Node ID {node.node_id} already exists in field.")
        self.nodes[node.node_id] = node
        self._next_node_id = max(self._next_node_id, node.node_id + 1)
        return node.node_id

    def create_node(
        self,
        position: np.ndarray,
        latent_valence: np.ndarray,
        velocity: Optional[np.ndarray] = None,
        core_potential: float = 1.0,
        field_radius: float = 5.0,
        field_intensity: float = 1.0,
        decay_gamma: float = 0.5,
    ) -> PhaseSpaceNode:
        node_id = self._next_node_id
        self._next_node_id += 1
        node = PhaseSpaceNode(
            node_id=node_id,
            position=position,
            latent_valence=latent_valence,
            velocity=velocity,
            core_potential=core_potential,
            field_radius=field_radius,
            field_intensity=field_intensity,
            decay_gamma=decay_gamma,
        )
        self.nodes[node_id] = node
        return node

    def compute_field_interactions(self) -> Dict[int, Dict[str, Any]]:
        """
        Computes pairwise latent valence interaction energy U_ij and causal tension gradient F_ij:
        U_ij = (v_i · v_j) * I_i * I_j * exp(-γ * ||x_i - x_j||)
        F_ij = -∇U_ij = U_ij * (x_j - x_i) / (||x_i - x_j|| + ε)
        """
        node_list = list(self.nodes.values())
        n = len(node_list)

        # Reset accumulated states
        for node in node_list:
            node.tension_force = np.zeros_like(node.position, dtype=np.float64)
            node.total_interference = 0.0

        field_states = {}

        for i in range(n):
            node_i = node_list[i]
            accumulated_tension = np.zeros_like(node_i.position, dtype=np.float64)
            total_interference = 0.0

            for j in range(n):
                if i == j:
                    continue
                node_j = node_list[j]

                delta_pos = node_j.position - node_i.position
                dist_sq = float(np.dot(delta_pos, delta_pos))
                max_radius = max(node_i.field_radius, node_j.field_radius)

                if dist_sq > max_radius * max_radius or dist_sq < 1e-8:
                    continue

                dist = np.sqrt(dist_sq)

                # 1. Latent Valence Vector (+@) Dot Product
                latent_dot = float(np.dot(node_i.latent_valence, node_j.latent_valence))

                # 2. Potential Field Decay & Energy
                decay = np.exp(-node_i.decay_gamma * dist)
                potential_energy = latent_dot * node_i.field_intensity * node_j.field_intensity * decay

                total_interference += abs(potential_energy)

                # 3. Directional Causal Tension Force (-∇U_latent)
                direction = delta_pos / (dist + 1e-8)
                accumulated_tension += direction * potential_energy

            node_i.tension_force = accumulated_tension
            node_i.total_interference = total_interference

            field_states[node_i.node_id] = {
                "total_interference": total_interference,
                "tension_force": accumulated_tension.copy(),
            }

        return field_states

    def step(self, dt: float = 0.01, damping: float = 0.1) -> Dict[str, Any]:
        """
        Executes one dynamic time-step of the causal phase field:
        1. Compute potential field interactions
        2. Update phase space trajectories (S_t, ΔS)
        3. Detect rupture events & instantiate (spawn) new nodes if threshold exceeded
        """
        self.compute_field_interactions()

        # Update node trajectories
        for node in self.nodes.values():
            node.update_physics(dt=dt, damping=damping)

        # Detect ruptures and spawn new nodes
        spawned_nodes = self._process_ruptures()

        return {
            "active_nodes": len(self.nodes),
            "spawned_this_step": len(spawned_nodes),
            "spawned_details": spawned_nodes,
        }

    def _process_ruptures(self) -> List[Dict[str, Any]]:
        """
        Rupture detection & Dimension Splitting Instantiation.
        When TotalInterference >= rupture_threshold or NaN occurs:
        The node's open +@ latent vector splits its dimension energy to spawn a new node in phase space.
        """
        if len(self.nodes) >= self.max_nodes:
            return []

        spawned = []
        ruptured_node_ids = []

        for node_id, node in list(self.nodes.items()):
            is_nan = np.isnan(node.total_interference) or np.any(np.isnan(node.tension_force))
            if is_nan or node.total_interference >= self.rupture_threshold:
                ruptured_node_ids.append(node_id)

        for parent_id in ruptured_node_ids:
            if len(self.nodes) >= self.max_nodes:
                break

            parent = self.nodes[parent_id]

            # Phase space offset for the spawned child
            offset_dir = parent.tension_force
            norm_offset = np.linalg.norm(offset_dir)
            if norm_offset > 1e-6:
                offset_dir = offset_dir / norm_offset
            else:
                offset_dir = np.random.randn(*parent.position.shape)
                offset_dir /= np.linalg.norm(offset_dir)

            child_position = parent.position + offset_dir * 0.5
            child_velocity = parent.velocity * 0.5 + offset_dir * 0.2

            # Mutate / split latent valence (+@) vector
            child_latent = parent.latent_valence.copy()
            # Orthogonalize or shift latent components to represent newly instantiated causal structure
            child_latent = np.roll(child_latent, 1) * 0.8 + np.random.randn(*child_latent.shape) * 0.1

            # Reduce parent intensity slightly (energy conservation)
            parent.field_intensity *= 0.85
            parent.total_interference *= 0.5

            # Instantiate child node
            child_node = self.create_node(
                position=child_position,
                latent_valence=child_latent,
                velocity=child_velocity,
                core_potential=parent.core_potential * 0.7,
                field_radius=parent.field_radius * 0.9,
                field_intensity=parent.field_intensity * 0.8,
                decay_gamma=parent.decay_gamma,
            )

            record = {
                "parent_id": parent_id,
                "child_id": child_node.node_id,
                "rupture_interference": parent.total_interference,
                "spawn_position": child_position.tolist(),
            }
            spawned.append(record)
            self.spawn_history.append(record)

        return spawned
