// ElysiaFusedKernel.hlsl - Fused TopIR Compute Shader
// Auto-generated by Elysia Operator Compiler (TopIR Back-end)
// Target: Direct3D12 / Vulkan Compute Shader (SM 6.5+)

cbuffer SystemConstants : register(b0) {
    float4 g_Params; // x: dt, y: K_0, z: gamma, w: Temp
    uint3  g_GridSize;
};

// 3D Field Texture Bindings
RWTexture3D<float4> g_QField    : register(u0); // Quaternion Rotor Field (x, y, z, w)
RWTexture3D<float4> g_VField    : register(u1); // Velocity Field (vx, vy, vz, reserved)
Texture3D<float>    g_TempField : register(t0); // Temperature Field

SamplerState g_LinearSampler : register(s0);

// Auxiliary Quaternion Operations
float4 quat_mul(float4 q1, float4 q2) {
    return float4(
        q1.w*q2.xyz + q2.w*q1.xyz + cross(q1.xyz, q2.xyz),
        q1.w*q2.w - dot(q1.xyz, q2.xyz)
    );
}

float4 quat_conj(float4 q) {
    return float4(-q.xyz, q.w);
}

[numthreads(8, 8, 8)]
void CS_EvolveSystem(uint3 dispatchThreadID : SV_DispatchThreadID) {
    if (any(dispatchThreadID >= g_GridSize)) return;

    float3 uvw = (float3(dispatchThreadID) + 0.5f) / float3(g_GridSize);
    float dt = g_Params.x;
    float K_0 = g_Params.y;
    float temp = g_TempField.SampleLevel(g_LinearSampler, uvw, 0);

    // 1. Read Current Center State
    float4 q_self = g_QField[dispatchThreadID];
    float3 v_self = g_VField[dispatchThreadID].xyz;

    // 2. Spatial Difference: Compute Curl(V) locally
    float3 v_px = g_VField[dispatchThreadID + uint3(1,0,0)].xyz;
    float3 v_nx = g_VField[dispatchThreadID - uint3(1,0,0)].xyz;
    float3 v_py = g_VField[dispatchThreadID + uint3(0,1,0)].xyz;
    float3 v_ny = g_VField[dispatchThreadID - uint3(0,1,0)].xyz;
    float3 v_pz = g_VField[dispatchThreadID + uint3(0,0,1)].xyz;
    float3 v_nz = g_VField[dispatchThreadID - uint3(0,0,1)].xyz;

    float3 curl_v = float3(
        (v_py.z - v_ny.z) - (v_pz.y - v_nz.y),
        (v_pz.x - v_nz.x) - (v_px.z - v_nx.z),
        (v_px.y - v_nx.y) - (v_py.x - v_ny.x)
    ) * 0.5f;

    // 3. Phase-Locking Torque (Sum of Neighbor Im(q_rel))
    float3 sync_torque = float3(0, 0, 0);
    int3 offsets[6] = { int3(1,0,0), int3(-1,0,0), int3(0,1,0), int3(0,-1,0), int3(0,0,1), int3(0,0,-1) };

    [unroll]
    for (int i = 0; i < 6; i++) {
        uint3 neighborCoord = clamp(dispatchThreadID + offsets[i], uint3(0,0,0), g_GridSize - 1);
        float4 q_neighbor = g_QField[neighborCoord];
        float4 q_rel = quat_mul(q_neighbor, quat_conj(q_self));
        sync_torque += q_rel.xyz; // Im(q_rel)
    }
    sync_torque *= K_0;

    // 4. Thermal Noise Calculation
    float noiseSeed = dot(dispatchThreadID, uint3(1, 149, 311)) + dt;
    float3 thermal_noise = float3(
        frac(sin(noiseSeed) * 43758.5453) - 0.5f,
        frac(sin(noiseSeed + 1.0) * 24614.63) - 0.5f,
        frac(sin(noiseSeed + 2.0) * 56445.12) - 0.5f
    ) * sqrt(2.0f * temp * dt);

    // 5. Total Torque & Langevin Integration on S^3
    float3 total_torque = curl_v + sync_torque + thermal_noise;
    float torque_len = length(total_torque) + 1e-6f;
    float half_angle = torque_len * dt * 0.5f;

    float4 dq = float4((total_torque / torque_len) * sin(half_angle), cos(half_angle));
    float4 q_next = normalize(quat_mul(dq, q_self));

    // 6. Local Coherence (Phi) Calculation
    float phi = saturate(length(sync_torque) / (K_0 * 6.0f + 1e-5f));

    // 7. Continuous Blending of Stress Momentum (Zero-Branch Neutralization)
    float w_solid = saturate((phi - 0.7f) * 10.0f);
    float w_gas   = saturate((0.3f - phi) * 10.0f);
    float w_fluid = 1.0f - w_solid - w_gas;

    float3 accel = (w_fluid * sync_torque - w_gas * float3(temp, temp, temp)) * dt;
    float3 v_next = v_self + accel;

    // 8. Write Back Updated State
    g_QField[dispatchThreadID] = q_next;
    g_VField[dispatchThreadID] = float4(v_next, 0.0f);
}
