#ifndef CAUSAL_ENGINE_EXTRACTION_ATTRACTOR_LAYER_HPP
#define CAUSAL_ENGINE_EXTRACTION_ATTRACTOR_LAYER_HPP

#include "causal_engine/core/preisach_soa.hpp"

#endif // CAUSAL_ENGINE_EXTRACTION_ATTRACTOR_LAYER_HPP
