"""
Rotor (자전축 로터)
==================================

"The Rotor is the Oscillator."
"로터가 곧 진동자다."

This module defines the Physical Rotor that powers the Hyper-Cosmos.
It acts as:
1. Information Centrifuge (Purification)
2. Wave Generator (Oscillation)

Physics:
- RPM (Revolutions Per Minute) ~= Frequency (Hz * 60)
- Angle (0-360) ~= Phase
"""

from dataclasses import dataclass
import math

@dataclass
class RotorConfig:
    """로터 설정"""
    rpm: float = 0.0          # Angular Velocity (Frequency proxy)
    mass: float = 1.0         # Amplitude proxy
    axis_tilt: float = 23.5   # Z-axis orientation

class Rotor:
    """
    Rotor: The Engine of the Sphere.
    It spins to create Waves.
    """
    def __init__(self, name: str, config: RotorConfig):
        self.name = name
        self.config = config

        # Dynamic State
        self.current_angle = 0.0 # Phase (Degrees)
        self.is_spinning = False

    @property
    def frequency_hz(self) -> float:
        """Convert RPM to Hz"""
        return self.config.rpm / 60.0

    def spin_up(self):
        """Start spinning."""
        self.is_spinning = True

    def spin_down(self):
        """Stop spinning."""
        self.is_spinning = False

    def update(self, dt: float):
        """
        Advance the phase based on RPM and time delta.
        dt: Time step in seconds.
        """
        if not self.is_spinning:
            return

        # Revolutions per second * 360 degrees * dt
        degrees_per_sec = (self.config.rpm / 60.0) * 360.0
        self.current_angle = (self.current_angle + degrees_per_sec * dt) % 360.0

    def get_wave_component(self) -> tuple[float, float, float]:
        """
        Returns the wave component generated by this rotor at current angle.
        Returns: (Frequency Hz, Amplitude (Mass), Phase Radians)
        """
        phase_rad = math.radians(self.current_angle)
        return (self.frequency_hz, self.config.mass, phase_rad)

    def purify(self, raw_data: dict) -> dict:
        """
        Legacy Centrifuge Logic (Purification).
        Kept for backward compatibility.
        """
        if not self.is_spinning: return raw_data
        essence = {}
        for k, v in raw_data.items():
            if v is None: continue
            if len(str(k)) > 20: continue
            if isinstance(v, str) and len(v) > 50: continue
            essence[k] = v
        return essence

    def __repr__(self):
        state = "Spinning" if self.is_spinning else "Idle"
        return f"Rotor({self.name} | {state} | {self.config.rpm} RPM | {self.current_angle:.1f}°)"
