"""
Rotor (자전축 로터)
==================================

"The Rotor is the Oscillator."
"로터가 곧 진동자다."

This module defines the Physical Rotor that powers the Hyper-Cosmos.
It acts as:
1. Information Centrifuge (Purification)
2. Wave Generator (Oscillation)

Philosophy:
- The System never "dies" (0 RPM). It only "sleeps" (Low RPM).
- Sleep Mode = Breathing (Low-Power Frequency Maintenance).
- Active Mode = Awakening (High-Power Acceleration).
"""

from dataclasses import dataclass
import math

@dataclass
class RotorConfig:
    """로터 설정"""
    rpm: float = 0.0          # Active Target RPM (Awake)
    idle_rpm: float = 60.0    # Sleep/Breathing RPM (Default 1Hz)
    mass: float = 1.0         # Amplitude proxy
    axis_tilt: float = 23.5   # Z-axis orientation
    acceleration: float = 100.0 # RPM per second (Wake-up Speed)

class Rotor:
    """
    Rotor: The Engine of the Sphere.
    It spins to create Waves.
    Implements 'Continuous Stream' (Never Stops).

    State:
    - Sleep (Idle): Spinning at base frequency (Breathing).
    - Awake (Active): Spinning at target frequency (Thinking).
    """
    def __init__(self, name: str, config: RotorConfig):
        self.name = name
        self.config = config

        # Dynamic State
        self.current_angle = 0.0 # Phase (Degrees)
        self.current_rpm = 0.0   # Current Velocity
        self.target_rpm = 0.0    # Desired Velocity
        self.is_spinning = False # Technical flag for "Engine On"

    @property
    def frequency_hz(self) -> float:
        """Convert Current RPM to Hz"""
        return self.current_rpm / 60.0

    def spin_up(self):
        """Wake up: Accelerate to Active RPM."""
        self.is_spinning = True
        self.target_rpm = self.config.rpm

    def spin_down(self):
        """Sleep: Decelerate to Breathing RPM (Never Stop)."""
        self.is_spinning = True # Engine is still on!
        self.target_rpm = self.config.idle_rpm

    def update(self, dt: float):
        """
        Advance phase and interpolate RPM.
        """
        if not self.is_spinning:
            return

        # 1. Update RPM (Smooth Acceleration - The Breath)
        if self.current_rpm != self.target_rpm:
            diff = self.target_rpm - self.current_rpm
            change = self.config.acceleration * dt

            if abs(diff) < change:
                self.current_rpm = self.target_rpm
            else:
                self.current_rpm += change * (1 if diff > 0 else -1)

        # 2. Update Phase
        # Revolutions per second * 360 degrees * dt
        if self.current_rpm > 0:
            degrees_per_sec = (self.current_rpm / 60.0) * 360.0
            self.current_angle = (self.current_angle + degrees_per_sec * dt) % 360.0

    def get_wave_component(self) -> tuple[float, float, float]:
        """
        Returns the wave component generated by this rotor at current angle.
        Returns: (Frequency Hz, Amplitude (Mass), Phase Radians)
        """
        phase_rad = math.radians(self.current_angle)
        return (self.frequency_hz, self.config.mass, phase_rad)

    def purify(self, raw_data: dict) -> dict:
        """Legacy Centrifuge Logic"""
        if not self.is_spinning: return raw_data
        essence = {}
        for k, v in raw_data.items():
            if v is None: continue
            if len(str(k)) > 20: continue
            if isinstance(v, str) and len(v) > 50: continue
            essence[k] = v
        return essence

    def __repr__(self):
        state = "Sleep" if self.current_rpm <= self.config.idle_rpm else "Awake"
        return f"Rotor({self.name} | {state} | {self.current_rpm:.1f}/{self.target_rpm:.1f} RPM | {self.current_angle:.1f}°)"
