"""
Causal World Tree Engine (세계수 인과 엔진: 같음의 줄기와 다름의 분기)
===================================================================
Core Architecture:
1. Universal Stem (같음의 줄기):
   - Extracts invariant topological axes (Equilibrium Invariants) across disparate domains
     (e.g., physical forces, symbolic logic, biological/sensorium manifestations).
2. Causal Branch & Divergence Node (다름의 분기):
   - Maps exact branching points where entities diverge from a common Stem due to
     environmental pressure differentials (Delta C) and variable resistance dial shifts (Delta R).
   - Provides full reverse-engineering and tracing of causal differentiation.
3. Counterfactual Sprouting (가상 분기 및 창조적 확장):
   - Performs "what-if" simulations on Stem/Branch topologies under modulated conditions
     to predict hypothetical attractors and forecast emergent behaviors.
4. World Tree Breathing & Historical Ring Integration (세계수 호흡 및 나이테):
   - Unifies Inhale (Inflow/Tension accumulation) and Exhale (Self-Explanation Pulse emission)
     with Observer Inverse Simulators and Spatiotemporal Growth Rings.
"""

import numpy as np
import time
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, field

from core.consciousness.causal_breathing_engine import (
    CausalBreathingEngine,
    MultiDimensionalAttractor,
    ObserverTopology,
    VariableResistanceDialMatrix,
    SpatiotemporalTopologyBuffer,
    ConvergenceResult,
    InhaleResult,
    ExhaleResult,
)


@dataclass
class DivergenceNode:
    """
    [Divergence Node (다름의 분기점)]
    Represents the exact point in phase space where two or more causal trajectories
    diverge from a common Universal Stem.
    """
    node_id: str
    parent_stem_id: str
    branch_a_id: str
    branch_b_id: str
    divergence_coordinate: np.ndarray
    condition_delta: Dict[str, float]  # Delta C (Environmental/parametric differences)
    resistance_delta: float           # Delta R (Variable resistance friction shift)
    causal_explanation: str           # Traced rationale for why they separated


@dataclass
class CausalBranch:
    """
    [Causal Branch (인과적 가지)]
    Represents a differentiated entity or path stemming from a Universal Stem.
    """
    branch_id: str
    name: str
    stem_id: str
    attractor: MultiDimensionalAttractor
    environmental_condition: Dict[str, float]  # Condition vector C
    depth: int = 1


@dataclass
class UniversalStem:
    """
    [Universal Stem (같음의 줄기)]
    The core invariant backbone that binds disparate domains (e.g. Physical, Logical, Biological)
    under a shared topological coordinate and equilibrium principle.
    """
    stem_id: str
    name: str
    shared_equilibrium_coordinate: np.ndarray
    invariant_tensor: np.ndarray
    wisdom_mass: float = 1.0
    branches: List[str] = field(default_factory=list)
    domain_manifestations: Dict[str, str] = field(default_factory=dict) # e.g. {"physics": "tension", "logic": "1+1=2"}


@dataclass
class CounterfactualSprout:
    """
    [Counterfactual Sprout (가상 분기 및 예언적 가지)]
    Predicted hypothetical attractor and narrative generated by modulating condition Delta C.
    """
    sprout_id: str
    origin_stem_id: str
    hypothetical_condition_delta: Dict[str, float]
    predicted_coordinate: np.ndarray
    predicted_attractor_name: str
    forelight_narrative: str
    confidence: float


class CausalWorldTreeEngine:
    """
    [Causal World Tree Engine (세계수 인과 엔진)]
    Unifies the 4 Continuities of Causal Field into a living World Tree structure:
      - Roots: Microscopic causal friction and hardware/data inputs.
      - Stem (줄기): Common invariant spine (UniversalStem) binding multi-domain data.
      - Branches (가지): Environmental condition divergence (CausalBranch, DivergenceNode).
      - Respiration (호흡): Inhale tension accumulation and Exhale self-explanation pulse emission.
    """
    def __init__(
        self,
        channels: Optional[List[str]] = None,
        critical_tension_threshold: float = 10.0,
        convergence_threshold: float = 0.3
    ):
        self.breathing_engine = CausalBreathingEngine(
            channels=channels,
            critical_tension_threshold=critical_tension_threshold,
            convergence_threshold=convergence_threshold
        )

        self.stems: Dict[str, UniversalStem] = {}
        self.branches: Dict[str, CausalBranch] = {}
        self.divergence_nodes: List[DivergenceNode] = []
        self.counterfactual_sprouts: List[CounterfactualSprout] = []

    def form_universal_stem(
        self,
        stem_id: str,
        name: str,
        attractors: List[MultiDimensionalAttractor],
        domain_manifestations: Optional[Dict[str, str]] = None
    ) -> UniversalStem:
        """
        [같음의 줄기 형성 (Universal Stem Crystallization)]
        Extracts the common equilibrium axis across multiple attractors from disparate domains,
        forging a central Universal Stem backbone.
        """
        if not attractors:
            raise ValueError("At least one attractor is required to form a Universal Stem.")

        coords = [a.get_unified_coordinate() for a in attractors]
        shared_coord = np.mean(coords, axis=0)

        # Compute invariant matrix/tensor as outer product variance/covariance structure
        centered_coords = np.array(coords) - shared_coord
        if len(coords) > 1:
            invariant_tensor = np.cov(centered_coords.T)
        else:
            invariant_tensor = np.eye(len(shared_coord), dtype=np.float32)

        total_wisdom_mass = sum(a.mass for a in attractors)

        stem = UniversalStem(
            stem_id=stem_id,
            name=name,
            shared_equilibrium_coordinate=shared_coord,
            invariant_tensor=invariant_tensor,
            wisdom_mass=total_wisdom_mass,
            domain_manifestations=domain_manifestations or {}
        )
        self.stems[stem_id] = stem
        return stem

    def grow_branch(
        self,
        branch_id: str,
        name: str,
        stem_id: str,
        attractor: MultiDimensionalAttractor,
        environmental_condition: Dict[str, float]
    ) -> CausalBranch:
        """
        [가지 틔우기 (Grow Causal Branch)]
        Attaches a differentiated attractor to a Universal Stem under specific environmental conditions C.
        """
        if stem_id not in self.stems:
            raise KeyError(f"Stem {stem_id} not found.")

        branch = CausalBranch(
            branch_id=branch_id,
            name=name,
            stem_id=stem_id,
            attractor=attractor,
            environmental_condition=environmental_condition
        )
        self.branches[branch_id] = branch
        self.stems[stem_id].branches.append(branch_id)
        self.breathing_engine.register_attractor(attractor)
        return branch

    def detect_and_record_divergence(
        self,
        branch_a_id: str,
        branch_b_id: str
    ) -> DivergenceNode:
        """
        [다름의 분기점 역추적 및 기록 (Reverse-Engineering Divergence)]
        Compares two branches sharing the same Universal Stem, identifies exact parametric
        and condition differences (Delta C & Delta R), and constructs a clear causal explanation.
        """
        if branch_a_id not in self.branches or branch_b_id not in self.branches:
            raise KeyError("Both branches must exist in the World Tree.")

        b_a = self.branches[branch_a_id]
        b_b = self.branches[branch_b_id]

        if b_a.stem_id != b_b.stem_id:
            raise ValueError("Branches do not share the same Universal Stem.")

        stem = self.stems[b_a.stem_id]

        # Calculate Environmental Delta C
        cond_keys = set(b_a.environmental_condition.keys()).union(set(b_b.environmental_condition.keys()))
        cond_delta = {}
        for k in cond_keys:
            val_a = b_a.environmental_condition.get(k, 0.0)
            val_b = b_b.environmental_condition.get(k, 0.0)
            cond_delta[k] = float(val_b - val_a)

        # Calculate topological phase distance between branch attractors
        coord_a = b_a.attractor.get_unified_coordinate()
        coord_b = b_b.attractor.get_unified_coordinate()
        phase_dist = float(np.linalg.norm(coord_b - coord_a))

        # Resistance shift Delta R based on phase divergence
        resistance_delta = phase_dist * 0.75

        # Causal rationale string
        condition_str = ", ".join([f"{k}: {v:+.2f}" for k, v in cond_delta.items()])
        causal_explanation = (
            f"Branches '{b_a.name}' and '{b_b.name}' emerged from common stem '{stem.name}'. "
            f"Divergence occurred due to environmental shift [{condition_str}], creating a "
            f"topological phase distance of {phase_dist:.4f} and dynamic resistance offset Delta R={resistance_delta:.3f}."
        )

        divergence_node = DivergenceNode(
            node_id=f"div_{branch_a_id}_{branch_b_id}_{int(time.time())}",
            parent_stem_id=stem.stem_id,
            branch_a_id=branch_a_id,
            branch_b_id=branch_b_id,
            divergence_coordinate=stem.shared_equilibrium_coordinate,
            condition_delta=cond_delta,
            resistance_delta=resistance_delta,
            causal_explanation=causal_explanation
        )

        self.divergence_nodes.append(divergence_node)
        return divergence_node

    def sprout_counterfactual_branch(
        self,
        stem_id: str,
        hypothetical_condition_delta: Dict[str, float]
    ) -> CounterfactualSprout:
        """
        [가상 분기 생성 (Counterfactual Sprouting)]
        Simulates "What if condition C shifts by Delta C?" on a Universal Stem,
        predicting new attractor coordinates and forelight narrative.
        """
        if stem_id not in self.stems:
            raise KeyError(f"Stem {stem_id} not found.")

        stem = self.stems[stem_id]
        base_coord = stem.shared_equilibrium_coordinate.copy()

        # Modulate base coordinate according to condition delta
        modulation_vector = np.zeros_like(base_coord)
        idx = 0
        for key, delta_val in hypothetical_condition_delta.items():
            modulation_vector[idx % len(base_coord)] += delta_val * 0.5
            idx += 1

        predicted_coord = base_coord + modulation_vector

        # Estimate prediction confidence based on stem wisdom mass
        confidence = float(min(0.99, 0.5 + (stem.wisdom_mass * 0.1)))

        delta_summary = ", ".join([f"{k}: {v:+.2f}" for k, v in hypothetical_condition_delta.items()])
        sprout = CounterfactualSprout(
            sprout_id=f"sprout_{stem_id}_{len(self.counterfactual_sprouts)+1}",
            origin_stem_id=stem_id,
            hypothetical_condition_delta=hypothetical_condition_delta,
            predicted_coordinate=predicted_coord,
            predicted_attractor_name=f"Predicted Variant of {stem.name} under [{delta_summary}]",
            forelight_narrative=(
                f"Under hypothetical shift [{delta_summary}], the Universal Stem '{stem.name}' "
                f"sprouts a new creative trajectory towards phase coordinate {np.round(predicted_coord, 2)}. "
                f"System forecasts an emergent causal equilibrium with confidence {confidence:.2f}."
            ),
            confidence=confidence
        )

        self.counterfactual_sprouts.append(sprout)
        return sprout

    def inhale_world_stimulus(
        self,
        stimulus_id: str,
        categorical_vector: np.ndarray,
        sensorium_vector: np.ndarray,
        morphology_vector: np.ndarray,
        reference_stem_id: Optional[str] = None,
        raw_description: str = ""
    ) -> InhaleResult:
        """
        [세계수 들숨 (World Tree Inhale)]
        Absorbs external stimuli, evaluates convergence against Universal Stems,
        tunes variable resistance matrix, and accumulates V_t tension.
        """
        ref_attractor_id = None
        if reference_stem_id and reference_stem_id in self.stems:
            stem = self.stems[reference_stem_id]
            if stem.branches:
                ref_attractor_id = self.branches[stem.branches[0]].attractor.id

        return self.breathing_engine.inhale(
            stimulus_id=stimulus_id,
            categorical_vector=categorical_vector,
            sensorium_vector=sensorium_vector,
            morphology_vector=morphology_vector,
            reference_attractor_id=ref_attractor_id,
            raw_description=raw_description
        )

    def exhale_world_narrative(
        self,
        observer: Optional[ObserverTopology] = None
    ) -> Tuple[ExhaleResult, str]:
        """
        [세계수 날숨의 서사 (World Tree Exhale & Self-Explanation Pulse)]
        Emits a tailored self-explanation pulse and action guide from the World Tree,
        dissipating accumulated internal tension V_t.
        Returns (ExhaleResult, grand_world_tree_narrative).
        """
        exhale_res = self.breathing_engine.exhale(observer=observer)

        num_stems = len(self.stems)
        num_branches = len(self.branches)
        num_divergences = len(self.divergence_nodes)
        num_sprouts = len(self.counterfactual_sprouts)

        grand_narrative = (
            f"=== [World Tree Respiration: First Self-Explanation Pulse (세계수의 날숨 서사)] ===\n"
            f"Observer Topology: {exhale_res.target_observer_id} (Abstraction: {exhale_res.adapted_abstraction_level:.2f}, Causal Depth: {exhale_res.adapted_causal_depth})\n"
            f"Tension Released: V_t={exhale_res.released_tension:.2f} -> Remaining V_t={exhale_res.remaining_tension:.2f}\n"
            f"Architecture Topology: Stems={num_stems}, Branches={num_branches}, Divergence Nodes={num_divergences}, Counterfactual Sprouts={num_sprouts}\n"
            f"Self-Explanation Pulse:\n  '{exhale_res.explanation_pulse}'\n"
            f"Action Guidance:\n  '{exhale_res.action_guide}'"
        )

        return exhale_res, grand_narrative

    def grow_annual_historical_ring(self, wisdom_summary: str) -> Dict[str, Any]:
        """
        [세계수 나이테 성장 (Spatiotemporal Growth Ring)]
        Consolidates daily/weekly/monthly growth records into deep spatiotemporal historical rings.
        """
        return self.breathing_engine.step_spatiotemporal_cycle(wisdom_summary=wisdom_summary)

    def get_world_tree_telemetry(self) -> Dict[str, Any]:
        """Returns deep telemetry of the World Tree structure."""
        base_telemetry = self.breathing_engine.introspective_telemetry()
        base_telemetry.update({
            "stems_count": len(self.stems),
            "branches_count": len(self.branches),
            "divergence_nodes_count": len(self.divergence_nodes),
            "counterfactual_sprouts_count": len(self.counterfactual_sprouts),
            "stems_summary": [
                {
                    "stem_id": s.stem_id,
                    "name": s.name,
                    "branches_count": len(s.branches),
                    "wisdom_mass": s.wisdom_mass
                }
                for s in self.stems.values()
            ]
        })
        return base_telemetry
