import math

class SemanticVoxel:
    def __init__(self, name=None, coords=None, mass=0.0, frequency=0.0, is_anchor=False):
        self.name = name
        self.coords = coords

        # Legacy compatibility handling
        self.frequency = frequency
        self.is_anchor = is_anchor
        self.quaternion = None
        if coords:
            from pyquaternion import Quaternion
            if len(coords) == 4:
                self.quaternion = Quaternion(coords[3], coords[0], coords[1], coords[2]) # w, x, y, z
            else:
                self.quaternion = Quaternion(1.0, 0.0, 0.0, 0.0)
        else:
            from pyquaternion import Quaternion
            self.quaternion = Quaternion(1.0, 0.0, 0.0, 0.0)

        self.inbound_edges = []
        self.outbound_edges = []

        # [DIGITAL GENERAL RELATIVITY]
        # 'Mass' is dead. We now use base_spin and Vortex Tension.
        # However, to avoid breaking existing legacy modules parsing 'mass',
        # we will alias it temporarily, or calculate tension dynamically.
        self.base_spin = mass

    @property
    def vortex_tension(self):
        """
        The rotational tension/torque generated by causal tethers wrapping around this coordinate.
        This replaces 'mass'. The more inbound tethers, the faster/denser the spin.
        """
        return self.base_spin + (len(self.inbound_edges) * 5.0)

    @property
    def mass(self):
        """Legacy alias for backward compatibility with older modules."""
        return self.vortex_tension

    @mass.setter
    def mass(self, value):
        """Legacy setter trap."""
        pass

    def distance_to(self, other_voxel):
        if not self.coords or not other_voxel.coords:
            return float('inf')
        return math.sqrt(sum((a - b)**2 for a, b in zip(self.coords, other_voxel.coords)))
