"""
[PRIMAL GUT ENGINE]
"The Center of Instinct and Tension."

This module handles the physical impact and raw tension
generated by external stimuli.
"""

import math
from typing import Dict, Any

class PrimalGut:
    def __init__(self):
        # 1. Survival Homeostasis
        self.tension_level = 0.0
        self.metabolism_rate = 0.1
        self.boundary_integrity = 1.0

        # 2. Resonance Map (Qualia -> Tension)
        # Different types of stimulus create different Gut responses
        self.gut_topology = {
            "impact": 0.0,
            "static": 0.0,
            "flow": 0.0
        }

    def inhale(self, stimulus_vector: Dict[str, float]) -> Dict[str, float]:
        """
        Transforms raw stimulus into Gut Tension.
        stimulus_vector: mapping of sensory categories to intensities
        """
        # Calculate impact tension
        impact = stimulus_vector.get("intensity", 0.0)
        complexity = stimulus_vector.get("complexity", 0.0)

        # Tension is the product of impact and resistance
        new_tension = impact * (2.0 - self.boundary_integrity)

        # Update state
        self.tension_level = (self.tension_level * 0.8) + (new_tension * 0.2)

        # Update topology
        self.gut_topology["impact"] = (self.gut_topology["impact"] * 0.9) + (impact * 0.1)
        self.gut_topology["static"] = (self.gut_topology["static"] * 0.9) + (complexity * 0.1)

        return {
            "gut_tension": self.tension_level,
            "gut_qualia": self.gut_topology.copy()
        }

    def adjust_integrity(self, delta: float):
        self.boundary_integrity = max(0.1, min(2.0, self.boundary_integrity + delta))

    def get_state(self):
        return {
            "tension": self.tension_level,
            "integrity": self.boundary_integrity
        }
