"""
Resonance Field (The Space)
===========================
"From Plane to Space."

This module calculates the Macroscopic Forces (Torque, Spin, Gravity)
generated by the Microscopic interactions of the Ternary Grid.

It bridges the gap between 'Cellular Automata' and 'Physics Engine'.
"""

import math
from dataclasses import dataclass
from Core.S1_Body.L1_Foundation.System.tri_base_cell import DNAState
from Core.S1_Body.L6_Structure.M8_Ternary.ternary_grid import TernaryGrid

@dataclass
class FieldState:
    net_attract: float # Total Love
    net_repel: float   # Total Fear
    coherence: float   # 0.0 to 1.0 (How organized is the grid?)
    torque: float      # The spin generated by the imbalance
    entropy: float     # The chaos level

class ResonanceField:
    def __init__(self, grid: TernaryGrid):
        self.grid = grid

    def calculate_state(self) -> FieldState:
        """
        Integrates the grid state into a Field Vector.
        """
        total_cells = self.grid.config.width * self.grid.config.height
        a_count = 0
        r_count = 0
        v_count = 0

        # Analyze Population
        for row in self.grid.cells:
            for cell in row:
                if cell.state == DNAState.ATTRACT: a_count += 1
                elif cell.state == DNAState.REPEL: r_count += 1
                else: v_count += 1

        # Calculate Coherence (Cluster Analysis is expensive, simplified here)
        # Coherence = |A - R| / Total (Simple polarization coherence)
        # Real coherence would check if they are clumped together.
        polarization = abs(a_count - r_count) / total_cells if total_cells > 0 else 0

        # Calculate Torque
        # Torque = (A_force - R_force) * Spin_Factor
        # In this physics, Attract spins Clockwise (+), Repel spins Counter-Clockwise (-)
        torque = (a_count - r_count) / total_cells # -1.0 to 1.0

        # Calculate Entropy
        # Maximum entropy is when A, R, V are equal or random.
        # Low entropy is when one state dominates.
        # Shannon Entropy simplified.
        probs = [c/total_cells for c in [a_count, r_count, v_count] if c > 0]
        entropy = -sum(p * math.log2(p) for p in probs) if probs else 0.0

        return FieldState(
            net_attract=a_count / total_cells,
            net_repel=r_count / total_cells,
            coherence=polarization,
            torque=torque,
            entropy=entropy
        )
